### ISSUE TITLE
incompatibility with some stuff in gadgetsmenu

### ISSUE THREAD

**Issue by coolpvpv1** [Elikill58/Negativity#10]
heres the plugin first of all https://www.spigotmc.org/resources/gadgetsmenu-1-8-1-14-4.10885/ (over 132k people have downloaded and used this) if you click on the nether star go to gadgets go to fun & games then choose the diving board gadget walk on the board where it launches you up in the air to land in the water you will flag the crap out of step and fly heres another false go to fun & games again then choose the trampoline gadget on then use it and just go on the trampoline and you flag the crap out of fly and step and sometimes spider heres another false now go to gadgets then movement and choose the rocket gadget use the rocket gadget then when you go into the air with it you false spider  and sometimes step then at the end when the rocket goes away you false fly and i think thats all the falses i could find

**Comment by Elikill58** [comment]
You have a free version ?
And can you finish your sentences ? xD
Finally, i will check it.

**Comment by coolpvpv1** [comment]
> You have a free version ?
> And can you finish your sentences ? xD
> Finally, i will check it.

new issue https://github.com/Elikill58/Negativity/issues/23
