### ISSUE TITLE
forge wurst mod No defense

### ISSUE THREAD

**Issue by taomrp** [Elikill58/Negativity#101]
spongeforge-1.12.2-2825-7.1.6
Negativity-1.6

Can we focus on wurst
Cheating MOD:  ForgeWurst-0.9-MC1.12.2.jar
https://www.wurstclient.net/download/

**Comment by Elikill58** [comment]
Can you explain ? Nothing is detected ?

**Comment by taomrp** [comment]
Yes, Press the G key to fly directly
there are no prompts on the console

Download test recommended
https://github.com/taomrp/Wurst

**Comment by Elikill58** [comment]
Only the fly isn't detected ?

**Comment by Elikill58** [comment]
No answer. After test (With HuyMCYTB on discord), we get alert.
Create new issue if you find new bypass.
