### ISSUE TITLE
Sneak False Positive

### ISSUE THREAD

**Issue by bertugarangou** [Elikill58/Negativity#103]
**Describe the bug**
False positive with Sneak when running and inmediately sneaking. Doesn't matter if keeping pressing run key or realising it.

**Your plugin version**
1.6

**Your platform version (and precise the platforme (spigot/sponge))**
PaperSpigot # 152. Minecraft 1.15.2.

**Screenshots**
https://imgur.com/a/b0zxJRD

**Error / Logs**
https://hastebin.com/oribulaxoy.css

**Comment by Elikill58** [comment]
Your serveur version is 1.15.2 ?

**Comment by bertugarangou** [comment]
yes, sorry
