### ISSUE TITLE
Spider false positive when in scaffolding block

### ISSUE THREAD

**Issue by bertugarangou** [Elikill58/Negativity#104]
**Describe the bug**
Detects Spider hack when climbing through scaffoldings.

**Your plugin version**
1.6 default config.

**Your platform version (and precise the platforme (spigot/sponge))**
PaperSpigot # 152. Minecraft 1.15.2.

**Error / Logs**
https://hastebin.com/eyudikihaw.css.

**Comment by Elikill58** [comment]
Only the Spider is a false positive ?
To disable this alert (while waiting that i fix it) you can put "reliability_alert" to up than 65

**Comment by bertugarangou** [comment]
Actually all that appear in hastebin clipboard. OK!
