### ISSUE TITLE
False Flags (Spider/FastStairs)

### ISSUE THREAD

**Issue by tombola46** [Elikill58/Negativity#105]
**Describe the bug**
1.Spider false flag - when you are climbing up a ladder
2.Faststairs false flag - when pressing space on stairs

**Your plugin version**
1.6

**Your platform version (and precise the platforme (spigot/sponge))**
Spigot 1.8.8

**Screenshots**
none

**Error / Logs**
https://paste.ubuntu.com/p/kbmwMyGtyB/

**Additional context**
none

**Comment by Elikill58** [comment]
1. Thanks for report
2. Duplicate of #102
