### ISSUE TITLE
Error Login Players

### ISSUE THREAD

**Issue by diaverso** [Elikill58/Negativity#11]
**Describe the bug**
When a user enters, an error comes out and kicks the user

**Your plugin version**
1.2.2

**Your spigot version**
spongeforge-1.12.2-2838-7.1.7-RC3880

**Screenshots**
No ScreenShot

**Additional context**
Used Modpack SevTech
Latest: https://gist.github.com/diaverso/b52cd009b6f891243ded5561133f1474

**Comment by Elikill58** [comment]
Hello,

Can you precise the error ?

**Comment by diaverso** [comment]
This is the error that gives me every time a user trains to enter and in the end he expels it.
https://gist.github.com/diaverso/1fed4fc927e20c95ba3f600a17542877

**Comment by Elikill58** [comment]
Fixed in commit 3df2d3a620305546f38df85c6bc0be5f3eea1410. Reason: FlyingReason can create problem sometimes.
