### ISSUE TITLE
Fly false positive

### ISSUE THREAD

**Issue by eereeska** [Elikill58/Negativity#110]
**Describe the bug**
Plugin has spammed chat with fly detections for player which just swimming 
Nice update

**Your plugin version**
1.6.1

**Your platform version (and precise the platforme (spigot/sponge))**
Paper 1.14.4.

**Screenshots**
https://imgur.com/a/O0yvf2w

**Comment by Elikill58** [comment]
Hello,

Thanks for report, it's fix.
I'm doing this for free, so please avoid "Nice update".
