### ISSUE TITLE
Error detection, spam console

### ISSUE THREAD

**Issue by diaverso** [Elikill58/Negativity#12]
**Describe the bug**
When it detects a cheto, errors appear on the console and it sparks

**Your plugin version**
version=1.3.2

**Your spigot version**
spongeforge-1.12.2-2838-7.1.7-RC3880

**Screenshots**
https://i.imgur.com/bci0oRF.gifv

**Error / Logs**
https://gist.github.com/diaverso/3b4a79006187e324cfe42dd016096dc0

**Additional context**
none

**Comment by Elikill58** [comment]
Do you get error on server startup or when player join ?
(I'm checking the error)

**Comment by RedNesto** [comment]
This issue has probably been fixed since then so I'll close this ticket.

If it still happens feel free to reopen it.
