### ISSUE TITLE
Allow to execute bans on the proxy

### ISSUE THREAD

**Issue by RedNesto** [Elikill58/Negativity#126]
**Explain the feature that you want**
Right now plugins can kick banned players but can't execute bans.
Their default configuration also does not contain a `ban` section.

It would be useful to allow proxies to execute bans, and add a new game server specific processor that will forward ban requests to the companion plugin.

**Additional context**
This was requested on the Discord server by Xitharis#0001

**Comment by Nevercold** [comment]
Like #120

**Comment by Elikill58** [comment]
No, because it concern ban (specially, AdvancedBan) support

**Comment by RedNesto** [comment]
In a way, it even supersedes it. The feature described here allows to use the `commands` processor on the proxy side in combination of a "forward to proxy" processor on the game server.
