### ISSUE TITLE
Error while enabling Negativity

### ISSUE THREAD

**Issue by Hybes** [Elikill58/Negativity#129]
**Describe the bug**
When the server starts, Negativity is unable to start

**Your plugin version**
1.7

**Your platform version (and precise the platforme (spigot/sponge))**
Paper-245

**Screenshots**
See pastebin

**Error / Logs**
https://pastebin.com/4hbPPXr3

**Additional context**
N/A

**Comment by Elikill58** [comment]
Hello,
What is your Java version ? because me (with Java 8, latest) and the same paper than you: it start.

**Comment by Hybes** [comment]
I'm using java 13? thats what my hosting shows as the latest version - maybe it's my mistake here :)

**Comment by Hybes** [comment]
After selecting a lower version of Java (11) it began working again

**Comment by Elikill58** [comment]
I'm using the latest version of Java 8, sorry for the mistake :)
Ok, I so it have been remove between Java 11 and Java 13. I will see a backup solution.
