### ISSUE TITLE
Rename Some Checks sense most names are weird

### ISSUE THREAD

**Issue by coolpvpv1** [Elikill58/Negativity#13]
Rename Autoregen to Regen 
Fastladders to Fastladder 
Speedhack to Speed 
Forcefield to Reach sense its only a reach check 
Autoclick to Autoclicker
Edited client to Timer
Autosteal to Cheatstealer
And AutoEat To FastEat

**Comment by Elikill58** [comment]
Hello,

Accepted change:
- Regen
- FastLadder
- Speed
- Timer
- AutoEat

Refused change:
- Reach : It's not only Reach detection, there is also fake player to detect player who hit player too quickly
- CheatStealer : It's not only for chest, it for all inventory

Edited in next commit.
