### ISSUE TITLE
Always give feedback to a command sender

### ISSUE THREAD

**Issue by RedNesto** [Elikill58/Negativity#135]
**Explain the feature that you want**

If I try to execute a ban or unban command but bans are disabled or the configured processor is invalid, the command will do nothing AND will not indicate the command sender that the action was not executed.

In all cases a command sender should receive feedback from a command they executed (usually via a chat message/console).

The ban example is the one I encountered and pushed me to file this issue, but there might be other cases, so I'll maintain a list of the places where this happens:
- [ ] ban and unban commands

**Comment by Elikill58** [comment]
Fixed in last commit in branch v2
