### ISSUE TITLE
Bypasses: Hack Client Depression

### ISSUE THREAD

**Issue by tombola46** [Elikill58/Negativity#145]
**Describe the bug**
This is list of bypasses of hack client Depression.
Download: https://www.mediafire.com/file/0ws3b6jvsh0w28i/Depression.rar/file

Fly:
- Hypixel, Glide, DACUpGlide(damage fly), ComboFloatZoom(damage fly)
Speed:
- NCPHop, Bhop, OnGround, SpartanHop, HypixelHop, AAC, HungryGames, CustomBHop(CustomSpeed from 0.2 to 0.64)
LongJump:
- HypixelZoom(damage longjump)
Step:
- NCP, Legit(you need to press space)

**Your plugin version**
1.8.1

**Your platform version (and precise the platforme (spigot/sponge))**
Spigot 1.8.8

**Screenshots**
none

**Error / Logs**
none

**Additional context**
none

**Comment by Elikill58** [comment]
I just test, after update some detection, and this is all detection that have bypass or I don't have tested it :
Fly:
- Glide, DACUpGlide(damage fly), ComboFloatZoom(damage fly)

Speed:
- Bhop, SpartanHop, AAC, HungryGames, CustomBHop(CustomSpeed from 0.2 to 0.64)

LongJump:
- HypixelZoom(damage longjump)

**Comment by tombola46** [comment]
Fly: ComboFloatZoom is detected
LongJump: HypixelZoom is detected
other are still bypassing

**Comment by Elikill58** [comment]
Fly: all are detected.

Speed not detected:
- Bhop
- HungryGames
- CustomBHop

Speed useless because doesn't help with speed (doesn't work on client side):
- SpartanHop
- AAC

**Comment by Elikill58** [comment]
Fixed in https://github.com/Elikill58/Negativity/commit/122bcff8f150d8625c3796cb5757546f2db5992a
