### ISSUE TITLE
NoFall seem as Speed

### ISSUE THREAD

**Issue by Chanakan5591** [Elikill58/Negativity#152]
**Describe the bug**
I've tried using NoFall but it flag as speed.

**Your plugin version**
1.8.1

**Your platform version (and precise the platforme (spigot/sponge))**
Paper Spigot 1.12.2

**Screenshots**
None

**Error / Logs**
no error as this seem to be false flag

**Additional context**
I have use NoFall cheat and jump down around 5 blocks, it will flag as using speed instead of NoFall

**Comment by Elikill58** [comment]
Hello,

What is your client ?
Can you send me proof file to exactly know how it detect Speed.
And, it's not a real bug because if you are using Nofall, you can be flag as Fly too. But, the same Fly check will not detect you without Nofall.

**Comment by Chanakan5591** [comment]
I have a small clip showing that jumping down with Nofall will be detect as speed instead of what is should be "Nofall" as you can see. Normally without nofall will not throw any speed flag.
[2020-06-16 16-28-26.zip](https://github.com/Elikill58/Negativity/files/4785698/2020-06-16.16-28-26.zip)

**Comment by Elikill58** [comment]
For me, on 1.8 or 1.12 server, with Wurst client, I get Speed AND NoFall alerts

**Comment by Riteo** [comment]
For me using Wurst 1.16.1 NoFall is always detected as Speed.

**Comment by Elikill58** [comment]
Seem to be fixed with Negativity 1.9.5
