### ISSUE TITLE
Configuring the detection by mods or permissions

### ISSUE THREAD

**Issue by Faelris** [Elikill58/Negativity#157]
It's about :
- [ ] A translation
- [ ] A new plugin support
- [ ] New detection
- [x] Other

**Explain the feature that you want**
Hi!

1. Thing is - im using a mod StepUp for alteration of vanilla autojump on my server (in a modpack).
It seems the plugin detects each use of a mod as a "Step" cheat. Is it possible to somehow configure that some mods are permitted to do such things without being detected as a cheat?
2. Same goes with /fly - i got Nucleus plugin installed on a server and set a "fly" permission for my admins and mods. When they use it and fly just straight up, the plugin detects it as a "Step" cheat. Is it possible to also add the check for permissions or smth?

Thank you in advance! 

**Additional context**

**Comment by Elikill58** [comment]
Hello,
1) If you allow the use of mods which create alert, i suggest you to disable the detection. Because I cannot know if the player use an hack or just the allowed mods.
2) You can use bypass. I.e. You add permission to mods, to use fly mods.
But if you disable Step, and it's what you get when flying, it will be fixed too

**Comment by Faelris** [comment]
Alright, thank you!
Also, I have Spartan weaponry installed - it allows the use of pikes, halberds and other weapons with extended reach (sometimes it triggers ForceField/KillAura. Is there a way to somehow configure the Reach component? Or like with Step, just disable?

**Comment by Elikill58** [comment]
You can edit the reach in the Forcefield part. But yes, if you have some mods that allow some cheat, I suggest you to disable. But in your case, I suggest to set an higher reach.

**Comment by Faelris** [comment]
Ok, understood, ty!

**Comment by Elikill58** [comment]
If you don't need more information, close the issue :)
