### ISSUE TITLE
ForceField is bugged. When there are many entities nearby and you hit them it will alert you for ForceField, When using grinders is very bad.

### ISSUE THREAD

**Issue by KingCurry12** [Elikill58/Negativity#162]
**Describe the bug**
ForceField is bugged. When there are many entities nearby and you hit them it will alert you for ForceField, When using grinders is very bad

**Your plugin version**
Plugin = 1.9

**Your platform version (and precise the platforme (spigot/sponge))**
1.16.1 Spigot

**Screenshots**
None.

**Error / Logs**
If applicable, add logs of error (copy/paste on pastebin/hastebin).

**Additional context**
When using grinders it will alert you for force field or when there are many entities nearby.

**Comment by Elikill58** [comment]
Hello,

Can you write your problem on the message, not on the title ?
With all needed information (Platform name and version ...)

**Comment by KingCurry12** [comment]
Sorry About that, New to GitHub

**Comment by Elikill58** [comment]
No problem. Can you send the file in /plugins/Negativity/proof/uuid.txt ?

**Comment by KingCurry12** [comment]
[Uploading 7ff5ffed-c720-34fe-b8d7-23d6472b4ca9.txt…]()
Go to this for force field: 2020-06-28 16:59:12.238:

**Comment by KingCurry12** [comment]
The contraption used to test it: https://imgur.com/GisJVzS

**Comment by KingCurry12** [comment]
Sorry for the late reply.

**Comment by Elikill58** [comment]
I understand, take your time ! (and 20 minutes is really good xd)
Thanks for report, I will fix it.
