### ISSUE TITLE
Xray alerts dont work

### ISSUE THREAD

**Issue by R4f4Lc** [Elikill58/Negativity#163]
**Describe the bug**
Xray alerts doesn´t work

**Your plugin version**
1.9
**Your platform version (and precise the platforme (spigot/sponge))**
sponge

**Additional context**
I test xray module and  doesn´t work. Users have xray and use it but negativity  doesn´t notify me.

**Comment by Elikill58** [comment]
Hello,
It's not a real bug because Xray is only for Minerate (now).

**Comment by R4f4Lc** [comment]
I have tried with other users that they only go to diamonds apart from rock and the alert does not go off. They have mined more than 200 diamonds with a peak of fortune

**Comment by Elikill58** [comment]
Fixed in V2 : https://github.com/Elikill58/Negativity/commit/2addaab746546dc84649640604c7ce102beb0131
