### ISSUE TITLE
Ban alt account

### ISSUE THREAD

**Issue by Elikill58** [Elikill58/Negativity#169]
It's about :
- [x] Other

**Explain the feature that you want**
If a player gets banned and the player has a lot of violations that if he/she joins the server on a alt account that he/she gets banned instantly (on the alt account) or something like that.

**Additional context**
Disabled by default

**Comment by SKBot08** [comment]
(I'm the same guy as who suggested this)
A little clearer:
So someone hacks on the server and gets banned, but he/she joins the server on a alt account that he/she has, the plugin detects that it's the same ip address as the other guy that is banned. So the anticheat trusts the alt account less (Normal kick/ban way: 1st vl: kick, 2nd vl: kick 2, 3rd vl: kick 3, 4th vl: ban 1 hour, 5th vl: ban 2 hours, and so on.

**Comment by averyanalex** [comment]
Yes, but, for example, 2 brothers, 1 cheater, another not
