### ISSUE TITLE
Not fully compatible with Geyser (bedrock) proxy on bungeecord network

### ISSUE THREAD

**Issue by kobenetwork** [Elikill58/Negativity#171]
Hello,

Im using a bedrock proxy called geyser, within the bungeecord i also use floodgate if that matters ( i don't think so)

with that said. a few problems occour when a bedrock player is playing on my servers.

*Blinking alerts (massive spam) when a player is just walking around ( might be latency related because of the translation it needs to do)
*Flying alerts when walking
*kicked for speed when player gets a knockback
and list goes on. did not yet tested everything .

If you need more information you can always contact me on discord. 
KobeNetwork#4442

cheerz

**Comment by Elikill58** [comment]
Seem to be fixed thanks to commit :

https://github.com/Elikill58/Negativity/commit/44f6eca1f8c09242bc6830e9fd458b3cce6d9f18 (FloodGate support)

https://github.com/Elikill58/Negativity/commit/4cb7f7fdc50ff45d7f29dc75b2e1962e36c5c5eb (Bedrock FP)
