### ISSUE TITLE
Kill aura

### ISSUE THREAD

**Issue by TimtimWinslow** [Elikill58/Negativity#173]
Hacks

Can you please add KillAura to cheats list it would be very helpful for all the people that using ur plugin @Elikill58

**Comment by Elikill58** [comment]
Hi,
KillAura, such as Reach, is actually incluse in Forcefield.
In v2, they will be exclude.
And, KillAura is already explained in wiki 😉

**Comment by TimtimWinslow** [comment]
Ok Thank u

**Comment by Elikill58** [comment]
Open new issue if need more informations, or come on discord for quick support !
