### ISSUE TITLE
False flag with 1.16 features

### ISSUE THREAD

**Issue by Elikill58** [Elikill58/Negativity#178]
**Describe the bug**
- [x] AutoSteal triggers when you shift-double-click stuff in chests to move large numbers of items. 
- [x] NoSlowDown triggers when a player runs on soul sand while wearing soul speed enchanted boots
- [x] AirJump triggers when a player jumps on the bottom half of stairs or slabs [only when there is an air block below them does this occur
- [x] Jesus triggers when walking on a bottom half slab placed over a source block of water

**Your plugin version**
1.9.4

**Your platform version (and precise the platforme (spigot/sponge))**
spigot 1.16

**Comment by spetznack** [comment]
Here is a video for the airjump one, though i realize the video is a lot darker than it shows in my minecraft game: 
https://youtu.be/Ygsn2QJnVoc

Here is the video for the autosteal one: 
https://youtu.be/FG70fHo0B6I

Here is the video for the Jesus one: 
https://youtu.be/PetYx8gMt3w

**Comment by spetznack** [comment]
In 1.9.5, Jesus still gives false positives when walking on a bottom half slab placed over a source block of water:
https://imgur.com/a/olE2wGv
