### ISSUE TITLE
Make alerts less verbose in chat

### ISSUE THREAD

**Issue by spetznack** [Elikill58/Negativity#179]
It's about :
- [ ] A translation
- [ ] A new plugin support
- [ ] New detection
- [x] Other

**Explain the feature that you want**
I just changed my language file to be a bit less verbose for moderators in chat. Maybe add something like this to the default?

**Additional context**
From this: 
![image](https://user-images.githubusercontent.com/1935616/93254077-12292f00-f798-11ea-83ca-84c1aa7eb1d9.png)

To this: 
![image](https://user-images.githubusercontent.com/1935616/93254093-19503d00-f798-11ea-8c3d-9ef89fc2e7e4.png)

**Comment by spetznack** [comment]
Better pictures to see how many alerts you can see in open chat window.. 
Before:
![image](https://user-images.githubusercontent.com/1935616/93254439-a4313780-f798-11ea-9473-056d10a4374e.png)
After:
![image](https://user-images.githubusercontent.com/1935616/93254476-adba9f80-f798-11ea-8bea-ac164d751a8b.png)

**Comment by Elikill58** [comment]
Hi, that's a good idea ! I will edit it soon
