### ISSUE TITLE
Jesus Check Doesn't Work

### ISSUE THREAD

**Issue by coolpvpv1** [Elikill58/Negativity#18]
Describe the bug
the jesus check just  doesn't work ive tried like 10+ clients tried all there jesus modules and they worked fine so idk if your jesus check is not working or what but im pretty sure its broken

Your plugin version
1.3.1

Your spigot version
1.8.8

Screenshots
None

Error / Logs
None

Additional context
None

**Comment by Elikill58** [comment]
Duplicated of Issue #9 , fixed on this commit : https://github.com/Elikill58/Negativity/commit/5da0bb7b7dd1e5d7f7d63247f49d8f3d2d6c625a

**Comment by Elikill58** [comment]
Wrong Issue (Sorry). I'm working on the Jesus detection.
