### ISSUE TITLE
Lily Pads\carpets on water triggers Jesus false positives

### ISSUE THREAD

**Issue by spetznack** [Elikill58/Negativity#180]
**Describe the bug**
False positive "Jesus" when standing on lily pad on the water. 

**Your plugin version**
1.9.4

**Your platform version (and precise the platforme (spigot/sponge))**
Paperspigot 1.16.3 build 194
![image](https://user-images.githubusercontent.com/1935616/93253155-c6c25100-f796-11ea-85e9-7590b30722a4.png)

**Screenshots**
https://youtu.be/PzlTD35LUec

**Error / Logs**
![image](https://user-images.githubusercontent.com/1935616/93252856-54517100-f796-11ea-88b5-a035bbfebd47.png)

**Additional context**
- We get no alerts when standing still 
- We do get alerts when rotating around or moving on top of the lily pad. 
- This is also the case for carpets on top of water, you can place carpets on water by placing it on the side of a block. 
- The lily-pad\carpet has to be 3 blocks away from the shore, 2 blocks away doesn't seem to trigger it. 
- It's a bit hard to tell why but some lily pads doesn't trigger and some do, we couldn't find any differences in particular that causes this so it is weird.

**Comment by Elikill58** [comment]
Video in private (cannot see it)

**Comment by spetznack** [comment]
Sorry, forgot to publish it. The link should work now.

**Comment by Elikill58** [comment]
Fixed in https://github.com/Elikill58/Negativity/commit/ea36aab76111409ea2e865c32cb84668f207e694
