### ISSUE TITLE
NoFall false positive for dropping down from water to air\transparent blocks

### ISSUE THREAD

**Issue by spetznack** [Elikill58/Negativity#181]
**Describe the bug**
Dropping down from water into air blocks or transparent blocks like trapdoors or signs then down on ground gives false positive for NoFall. 

**Your plugin version**
1.9.4

**Your platform version (and precise the platforme (spigot/sponge))**
paperspigot 1.16.3 build 194
![image](https://user-images.githubusercontent.com/1935616/93265785-6557ad80-f7a9-11ea-8379-714f1e761b68.png)

**Screenshots**
https://youtu.be/g1G2gQgwLdI

**Error / Logs**
![image](https://user-images.githubusercontent.com/1935616/93265719-4f49ed00-f7a9-11ea-9f0c-02f3eb214861.png)

**Additional context**

**Comment by eodrambo** [comment]
Can confirm

**Comment by spetznack** [comment]
Seems to be supressed heavily in 1.9.5 beta (posted on discord today), but still gives one or the other every now and then. 
https://www.youtube.com/watch?v=sr5gDEMbyJI

I can't replicate it consistently :S

**Comment by Elikill58** [comment]
Ok so it's very difficult to reproduce.
I will see if me, I can reproduce it, maybe I will just stay player more longer on a NoFall system
