### ISSUE TITLE
False positives for speed while jumping

### ISSUE THREAD

**Issue by eodrambo** [Elikill58/Negativity#182]
**Describe the bug**

- False positive for speed while sprinting & Jumping up stairs
- False positive for speed while sprinting & jumping down a 2 high corridor

**Your plugin version**
1.9.4

**Your platform version**
Paper-191

**Comment by eodrambo** [comment]
The bug is fixed while jumping down a corridor, 
however still exists and is reproducible when running and jumping up stairs. 
it also exists with auto jump on, and running up stairs.

**Comment by Elikill58** [comment]
Can you show me it ?

**Comment by Elikill58** [comment]
Failed to reproduce, seem to be fixed.
