### ISSUE TITLE
Spider false positive when on edge of water elevator

### ISSUE THREAD

**Issue by spetznack** [Elikill58/Negativity#183]
**Describe the bug**
When ascending a water elevator, but standing on the edge of the bubble water block then it triggers the spider no-cheat. 

**Your plugin version**
1.9.4 it says but it should be beta version (?) from discord. 

![image](https://user-images.githubusercontent.com/1935616/94490560-c2f6eb80-01e6-11eb-8c53-2436c9aa2a4b.png)

**Your platform version (and precise the platforme (spigot/sponge))**
paperspigot Build 194
![image](https://user-images.githubusercontent.com/1935616/94490421-85925e00-01e6-11eb-8c54-6877a884cbb6.png)

**Screenshots**
https://youtu.be/AjT4q1aDuzo

**Error / Logs**
See video, let me know if you need more info.

**Comment by Elikill58** [comment]
Fixed in https://github.com/Elikill58/Negativity/commit/549551d139968a94902d546df01d6d5ba95be177
