### ISSUE TITLE
Packet Hacks being marked as NoFall

### ISSUE THREAD

**Issue by dkim19375** [Elikill58/Negativity#185]
**Describe the bug**
Packet hacks such as AntiHunger are being marked as NoFall

**Your plugin version**
1.9.5

**Your platform version (and precise the platforme (spigot/sponge))**
Paper
Minecraft 1.15.2
Client 1.12.2, 1.15.2

**Screenshots**
![image](https://user-images.githubusercontent.com/65050767/94995654-a30c5280-056d-11eb-9c27-e91ea0215ba9.png)
![image](https://user-images.githubusercontent.com/65050767/94995664-b8817c80-056d-11eb-9114-1befa3792a3d.png)

**Error / Logs**
If applicable, add logs of error (copy/paste on pastebin/hastebin).

**Additional context**

**Comment by dkim19375** [comment]
https://i.imgur.com/jhsg31t.mp4

**Comment by Elikill58** [comment]
Such as it's a detection of hack, it's not a good way of play.
So, I don't want to fix it, because people don't have to do that. (And I think that it will be very difficult to fix)
