### ISSUE TITLE
WorldGuard support create NPE

### ISSUE THREAD

**Issue by spetznack** [Elikill58/Negativity#193]
Describe the bug
Got this error message in the console. 
This happened only 5-6 times during 5 minutes, haven't seen it in a long time since then. 
Not sure what triggered it so I don't know how to replicate it. :/

Worldguard version --> 7.0.4-beta1;bc551da

Your plugin version
Negativity_v2 16.10.2020

Your platform version (and precise the platforme (spigot/sponge))
PaperSpigot 1.16.3 build #212

Screenshots
NoFall_false-positive_when_jumping_in_a_2 5_high_space_where_you_stand_on_top_of_a_half-slab_with_ai

Error / Logs
https://gist.github.com/spetznack/8de809c7d15360efd7d3f5e795360058

Additional context

**Comment by Elikill58** [comment]
Fixed in next commit.
