### ISSUE TITLE
Running while holding jump in beacon field with speed II and jump boost II causes step 65% notification.

### ISSUE THREAD

**Issue by SnowyDwarf** [Elikill58/Negativity#196]
**Describe the bug**
see title

**Your plugin version**
v2

**Your platform version (and precise the platforme (spigot/sponge))**
PaperSpigot 1.16.3 build #212

**Comment by Elikill58** [comment]
I suggest you to make quick title and show more informations in issue.
Can you send me proof file ?

**Comment by spetznack** [comment]
Confirmed on Negativity_v2 16.10.2020

Description: jump_boost 1 and 2 effect gives step when jumping, seems to always trigger. The floor is made out of more than two layers of solid blocks where I was testing this. 

Tested in beacon with jump boost 2 but also by simply using "/effect give <player> minecraft:jump_boost 15 1" and then jump a couple times. Gives alert on first jump and all subsequent jumps. 

Proof file: https://gist.github.com/spetznack/a7e97a916745248bb97ab5666fe843e1

Jump boost 1 false positive screenshot: 
![jump_boost 1 effect gives step when jumping, seems to always trigger](https://user-images.githubusercontent.com/1935616/96607934-21e8e580-12f9-11eb-9f3e-f62b795ee303.gif)

Jump boost 2 false positive screenshot: 
![jump_boost 2 effect gives step when jumping, seems to always trigger](https://user-images.githubusercontent.com/1935616/96608204-62486380-12f9-11eb-85cb-9d45e7903a46.gif)
