### ISSUE TITLE
Sprinting on the surface of water in a speed II beacon field casuses Jesus as various high percentages.

### ISSUE THREAD

**Issue by SnowyDwarf** [Elikill58/Negativity#197]
**Describe the bug**
See title

**Your plugin version**
v2

**Your platform version (and precise the platforme (spigot/sponge))**
PaperSpigot 1.16.3 build #212

**Comment by spetznack** [comment]
Confirmed on Negativity_v2 16.10.2020

Description: Jesus false-positive when strafing on surface of water near beacon 

**From my testing, the following setup is required to replicate this:** 
- Player needs to have speed 1 or 2 effect from beacon or by using command /effect give <player> minecraft:speed 50 2
- Player must be wearing dept_strider 2 or 3 boots. (No boots or dept_strider 1 boots does not give alert)
- Strafing (not swimming) on the surface of water which is 2 blocks deep or deeper. (1 deep does not give alert) 

I am able to replicate this consistently with this setup. 

Proof file --> https://gist.github.com/spetznack/dd0d2ab6fc2bfa5b14362a38300c2d1f

Screenshot: 
![Jesus false-positive when strafing on surface of water](https://user-images.githubusercontent.com/1935616/96614819-d3d7e000-1300-11eb-98d6-2bc50a40d7bf.gif)
