### ISSUE TITLE
configs crash

### ISSUE THREAD

**Issue by InterVi** [Elikill58/Negativity#2]
config.conf

Line 59, need use double quotes:
`    cheats: "speedhack,fly"`

lang files:

Need use colon in sub-sections, like a
`  detection: {`

Logs:
https://pastebin.com/SNqsNWTV
https://pastebin.com/QqkSJXfS

**Comment by Elikill58** [comment]
Hello,
Because of your log, I see that you're on Sponge.
You're on which sponge version ? Negativity is build with Sponge for 1.12. I think for hte next version i will add 1.13 compatibility but right now i don't know if it works.

**Comment by InterVi** [comment]
spongevanilla-1.12.2-7.1.5-RC139

**Comment by Elikill58** [comment]
can you send the full file which create this problem ?

**Comment by Elikill58** [comment]
I forget to respond, but it have been fix a lot of commit before.
