### ISSUE TITLE
v2 NoFall false positive when jumping\landing on outer-edge of any block

### ISSUE THREAD

**Issue by spetznack** [Elikill58/Negativity#200]
Describe the bug
NoFall false positive when jumping\landing on outer-edge of any block. 

Your plugin version
Negativity_v2 20.10.2020

Your platform version (and precise the platforme (spigot/sponge))
PaperSpigot 1.16.3 build #212

Screenshots
![NoFall false positive when jumping\landing on outer-edge of any block](https://user-images.githubusercontent.com/1935616/96910329-9fe6f100-149f-11eb-9d03-c4038192ad26.gif)

Error / Logs
Proof file for these alerts: https://gist.github.com/spetznack/3c116727276e22db3c6220e8e3ce1c44

Additional context
Player has to land with center of player outside the block to trigger alert.

**Comment by Elikill58** [comment]
Seems to be fixed in https://github.com/Elikill58/Negativity/commit/02fd83d6fde5bccf532a2dd61c2b6a7c537310de
