### ISSUE TITLE
(tested with v2) PingSpoof not working

### ISSUE THREAD

**Issue by dkim19375** [Elikill58/Negativity#206]
**Describe the bug**
PingSpoof check does not work with 1000+ ping

**Your plugin version**
Latest.... https://github.com/Elikill58/Negativity/commit/c71848d95d65247ec827223905fa771ee7d0dcc6 probably

**Your platform version (and precise the platforme (spigot/sponge))**
Paper 1.15.2

**Screenshots**

**Error / Logs**
Just a bunch of nofall in proof file
**Additional context**
Stop calling it PongSpoof

**Comment by Elikill58** [comment]
After coming to v2.negativity.fr, alert of PingSpoof have been sent.
