### ISSUE TITLE
More Detailed Help Menu

### ISSUE THREAD

**Issue by dkim19375** [Elikill58/Negativity#207]
It's about 
- [x] Other

**Explain the feature that you want**
Show all commands in /negativity 

**Additional context**

**Comment by Elikill58** [comment]
The tab isn't enough ? 
![image](https://user-images.githubusercontent.com/17381066/99153961-712df600-26ac-11eb-8253-78a5e423057d.png)

Specially for 1.16, we can easily see all available commands

**Comment by dkim19375** [comment]
No

1. Does it really take that long to make a help menu
2. For me the tab doesn't work :/

**Comment by spetznack** [comment]
If its easy to implement then it is alway nice when it shows you only the commands you have permissions for

**Comment by dkim19375** [comment]
oh wat

**Comment by dkim19375** [comment]
> If its easy to implement then it is alway nice when it shows you only the commands you have permissions for

what do you mean?

**Comment by spetznack** [comment]
> > If its easy to implement then it is alway nice when it shows you only the commands you have permissions for
> 
> what do you mean?

If you dont have permissions for reload then dont show that there is a command /negativity reload

**Comment by dkim19375** [comment]
> > > If its easy to implement then it is alway nice when it shows you only the commands you have permissions for
> > 
> > 
> > what do you mean?
> 
> If you dont have permissions for reload then dont show that there is a command /negativity reload

welp for me it never shows the reload command, but I still have the perms
