### ISSUE TITLE
Command Request: /n verbose

### ISSUE THREAD

**Issue by dkim19375** [Elikill58/Negativity#208]
It's about :
- [ ] A translation
- [ ] A new plugin support
- [ ] New detection
- [x] Other

**Explain the feature that you want**
Shows alert to the player at x amount of alerts (set in config), with a default of 1. 

**Additional context**

**Comment by Elikill58** [comment]
Does this issue already make sens after adding an option like that in 226's issue ?

**Comment by dkim19375** [comment]
i dont think so
