### ISSUE TITLE
Pingspoof Disables All The Anticheats Checks

### ISSUE THREAD

**Issue by coolpvpv1** [Elikill58/Negativity#21]
Describe the bug
Big bug where you can disable all the anticheat checks simply by going on any client and using pingspoof or just use liquidbounce and do .pingspoof mindelay 1800 and .pingspoof maxdelay 2000 then turn on pingspoof wait for 15 seconds then try to fly or speed around at max speed and you wont flag at all its op

Your plugin version
1.3.1

Your platform version (and precise the platforme (spigot/sponge))
Spigot 1.8.8

Videos
https://streamable.com/r2t6o

Error / Logs
none cause its a disabler xd

Additional context
idk?

**Comment by Elikill58** [comment]
Hello,

This editing your ping. To avoid false positive, when your ping is too high, the alert is removed.
Check in the config, the "ping" configuration.
