### ISSUE TITLE
Tab complete issue

### ISSUE THREAD

**Issue by rudde0** [Elikill58/Negativity#215]
**Describe the bug**
When I try to /lp user ... and I can't see alternative tab completes and server kick me because of I timed out. (I can use LP commands via console but I can't execute as player)

**Your plugin version**
LuckPerms 5.2.32
Negativity 1.9.6

**Your platform version (and precise the platforme (spigot/sponge))**
Yatopia b20 (Paper fork)

**Comment by Elikill58** [comment]
Hi,
You don't have specific log in console ? Are you sure that it comes from my plugin ?
Do you have specific plugin like ProtocolLib, ProtocolSupport, ViaVersion ... 
You are running on MC 1.16.2 ?

**Comment by rudde0** [comment]
I have ProtocolLib, and I'm using MC 1.16.4 and no sorry there is no log in console.

**Comment by Elikill58** [comment]
Ok thanks, I will check

**Comment by Elikill58** [comment]
With latest build of spigot, LuckPerms 5.2.32, Negativity 1.9.6 and ProtocolLib 4.5.1 I don't have any problems.
Can you send me your Yatopia build ?

**Comment by rudde0** [comment]
https://api.yatopiamc.org/v2/build/20/download?branch=ver/1.16.4

**Comment by rudde0** [comment]
p.s. I'm using ProtocolLib 4.6.0 SNAPSHOT b478

**Comment by Elikill58** [comment]
Do you already have the issue ? And have to keep the plugin ? Because you're alone to have report this error

**Comment by rudde0** [comment]
I can't able to reproduce issue again but I can open this if issue still exists when I tested.
