### ISSUE TITLE
Speed check error?

### ISSUE THREAD

**Issue by Tiippex** [Elikill58/Negativity#218]
When using a speedhack, Negativity throws a nullpointer exception

Negativity version 2.0-ALPHA

git-Paper-368 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)

Error / Logs
https://hastebin.com/zihehihere.yaml

**Comment by Elikill58** [comment]
This error is produce by the same problem as #217 ;
Citizens NPC which are consider as real players
