### ISSUE TITLE
Support with DKbans

### ISSUE THREAD

**Issue by larssieboy18** [Elikill58/Negativity#219]
It's about :
A new plugin support

**Explain the feature that you want**
Hi there,

I would really like to see support for the ban plugin DKbans. It is a really nice ban plugin that I would like to use with Negativity.

**Additional context**
Link to plugin page: https://www.spigotmc.org/resources/dkbans-bansystem-playermanagement-json-mysql-sqlite-mongodb-bukkit-bungeecord.52570/

Thanks!

**Comment by Elikill58** [comment]
Added in https://github.com/Elikill58/Negativity/commit/0934acc2d1e691aaccdadf26aaf3b53ca36081ce
