### ISSUE TITLE
Reach Check False Flag

### ISSUE THREAD

**Issue by coolpvpv1** [Elikill58/Negativity#22]
Describe the bug
I was normally hitting a zombie with a knockback 2 sword and it was falsing reach (forcefield)

Your plugin version
1.3.2 (newest)

Your platform version (and precise the platforme (spigot/sponge))
Spigot 1.8.8

Video
https://streamable.com/9he4y

Error / Logs
Watch The Video

Additional context
None

**Comment by Elikill58** [comment]
Hello,

Can you send me the file Negativity\user\proof\yourUUID.txt ?

**Comment by Elikill58** [comment]
Closing because we got no response and impossible to reproduce same false flag.
