### ISSUE TITLE
Banning player "???" when anti cheat detection

### ISSUE THREAD

**Issue by JanimationsYT** [Elikill58/Negativity#220]
I was requested to make this by Eli so I did
Picture of logs https://gyazo.com/3028330d9f0adf80981b10051ba8fb15
I was sent an updated .jar but in the latest version this error still occurs iirc

**Comment by Elikill58** [comment]
Already fixed in https://github.com/Elikill58/Negativity/commit/866c16aeecb9a3e75b1922d7e7a04d4d3eabd262
