### ISSUE TITLE
Game-Breaking false positives

### ISSUE THREAD

**Issue by Jayma1322** [Elikill58/Negativity#223]
In 1.16.5, you cannot do the following:
Use the swim animation by sprinting in water (Kicks for Jesus)
Sprint jump with a 2 block high roof (Kicks for speed)

I understand the plugin wasn't built for this version but when the false positives are this game-breaking it becomes a major issue.

**Comment by Elikill58** [comment]
Cannot reproduce, seems to be fixed.
