### ISSUE TITLE
[BYPASS] Fly bypass with NCP & Spartan Fly 

### ISSUE THREAD

**Issue by dkim19375** [Elikill58/Negativity#224]
**Describe the bug**
You can fly with NCP and Spartan Fly, LiquidBounce
Note: #231 is for Sigma fly

**Your plugin version**
Commit https://github.com/Elikill58/Negativity/commit/151e22eabd7e06860e97d9cb83ec2fb780d03b56
v2

**Your platform version (and precise the platforme (spigot/sponge))**
Paper 1.8.8

**Screenshots**
I'm not on my pc right now :c

**Error / Logs**
No logs

**Additional context**

**Comment by Elikill58** [comment]
No bypass with Spartan of LiquidBounce
