### ISSUE TITLE
[BYPASS] Scaffold and speed

### ISSUE THREAD

**Issue by dkim19375** [Elikill58/Negativity#228]
**Describe the bug**
Scaffolding at very high speeds, making it very overpowered

**Your plugin version**
v2 beta, commit: https://github.com/Elikill58/Negativity/commit/468f4d1bfe1e4e06df0fcacd22a37cf3c6e3aab1

**Your server version (and the software type (spigot/sponge))**
Paper 1.16.4

**Screenshots**
https://streamable.com/u2j8ep

**Error / Logs**
No logs

**Additional context**
There are also a lot of other speed "bypasses"

**Comment by Elikill58** [comment]
![image](https://user-images.githubusercontent.com/17381066/112695843-117aff00-8e85-11eb-8af5-0b97a977f6cd.png)
Flag for multiple hacks.
