### ISSUE TITLE
[BYPASS] NoFall

### ISSUE THREAD

**Issue by dkim19375** [Elikill58/Negativity#229]
**Describe the bug**
NoFall Bypass

**Your plugin version**
v2 beta, commit: https://github.com/Elikill58/Negativity/commit/468f4d1bfe1e4e06df0fcacd22a37cf3c6e3aab1

**Your server version (and the software type (spigot/sponge))**
Paper 1.16.5

**Screenshots**
https://streamable.com/fl89lx

**Error / Logs**
No logs

**Additional context**
Sigma 5.0

**Comment by Elikill58** [comment]
Fixed with #239
