### ISSUE TITLE
[BYPASS] Flight - Spartan

### ISSUE THREAD

**Issue by dkim19375** [Elikill58/Negativity#231]
**Describe the bug**
Sigma 5.0 - Spartan flight bypass
Note: #224 is for Liquidbounce fly

**Your plugin version**
v2 beta, commit: https://github.com/Elikill58/Negativity/commit/468f4d1bfe1e4e06df0fcacd22a37cf3c6e3aab1

**Your server version (and the software type (spigot/sponge))**
Paper 1.16.5

**Screenshots**
https://streamable.com/mtem3p

**Error / Logs**
No logs

**Additional context**

**Comment by Elikill58** [comment]
Fixed in #239
