### ISSUE TITLE
[BYPASS] Fly - VeltPVP - Sigma 5.0 

### ISSUE THREAD

**Issue by dkim19375** [Elikill58/Negativity#232]
**Describe the bug**
You can bypass with VeltPVP Fly, with the speed set to 5.
It shows very little alerts.

**Your plugin version**
The version of Negativity that you are using

**Your server version (and the software type (spigot/sponge))**
Paper 1.16.5

**Screenshots**
https://streamable.com/evhtck

**Error / Logs**
https://paste.helpch.at/iwajawifap.coffeescript
(Logs from higher speed of VeltPvP fly which showed many alerts)

**Additional context**
Flying up tends to alert a lot

**Comment by Elikill58** [comment]
Seems to be fixed.
