### ISSUE TITLE
[BYPASS] Fly - Vanilla - Sigma 5

### ISSUE THREAD

**Issue by dkim19375** [Elikill58/Negativity#233]
**Describe the bug**
Fly bypass with vanilla fly, speed: 0.28

**Your plugin version**
v2, commit: https://github.com/Elikill58/Negativity/commit/468f4d1bfe1e4e06df0fcacd22a37cf3c6e3aab1

**Your server version (and the software type (spigot/sponge))**
Paper 1.16.5

**Screenshots**
https://streamable.com/r55nvr

**Error / Logs**
Speed 0.38: https://paste.helpch.at/luzafeheyo.coffeescript

**Additional context**

**Comment by Elikill58** [comment]
![image](https://user-images.githubusercontent.com/17381066/108563851-78474e80-7302-11eb-82a1-bf75bf3163a7.png)
I get alert for fly
