### ISSUE TITLE
[BYPASS] Step

### ISSUE THREAD

**Issue by dkim19375** [Elikill58/Negativity#234]
**Describe the bug**
NCP - timer: 0.4
Spider
bypasses
Sigma 5.0

**Your plugin version**
v2, commit: https://github.com/Elikill58/Negativity/commit/468f4d1bfe1e4e06df0fcacd22a37cf3c6e3aab1

**Your server version (and the software type (spigot/sponge))**
The version of your server

**Screenshots**

**Error / Logs**
If applicable, add logs of error (copy/paste on pastebin/hastebin).

**Additional context**

**Comment by Elikill58** [comment]
Seems to be fixed.
