### ISSUE TITLE
JumpPads Support

### ISSUE THREAD

**Issue by jokbon** [Elikill58/Negativity#238]
It's about :
- [x] A new plugin support

**Jump pads support for no false positives**
Support this https://www.spigotmc.org/resources/custom-jumppads-1-8-1-16.44876/
so it wont kick for no fall, fly etc, wont cancel ur action.

**Additional context**
Hello my name is karl, iam from reddit.

**Comment by Elikill58** [comment]
Seems to be fixed with #244
