### ISSUE TITLE
AntiKnockBack False Flag

### ISSUE THREAD

**Issue by coolpvpv1** [Elikill58/Negativity#24]
Describe the bug
sometimes when you get hit by a iron golem and dont move you will false antiknockback

Your plugin version
1.3.2

Your platform version (and precise the platforme (spigot/sponge))
Spigot 1.8.8

Video
https://streamable.com/wul18

Error / Logs
Watch The Video

Additional context
None

**Comment by Elikill58** [comment]
Hello,

Have you tried without any hack client ? Because, sometimes some hack create warn for other hack
