### ISSUE TITLE
When you get out of a boat or swim, flags for Jesus

### ISSUE THREAD

**Issue by CookieGuy123** [Elikill58/Negativity#242]
**Describe the bug**
On 1.16, when you do the new swimming, it sometimes flags for jesus. When on a boat and getting off, it flags for Jesus.

**Your plugin version**
1.9.8

**Your server version (and the software type (spigot/sponge))**
PaperMC 1.16.5

**Screenshots**
![image](https://user-images.githubusercontent.com/78625905/112676501-e40b6280-8e3e-11eb-9114-4f0edef56677.png)
![image](https://user-images.githubusercontent.com/78625905/112676533-ed94ca80-8e3e-11eb-8672-032c3b6237ff.png)
![image](https://user-images.githubusercontent.com/78625905/112676545-f1c0e800-8e3e-11eb-8071-53e24fa8ebb3.png)
![image](https://user-images.githubusercontent.com/78625905/112676553-f4bbd880-8e3e-11eb-8255-6fc0ac2b8ab9.png)
(my admin watching the player who flags)

**Error / Logs**
https://mclo.gs/DouD6F1

**Additional context**
 I love this anticheat, it's just that it sometimes kicks for jesus when that happens/

**Comment by Elikill58** [comment]
Seems to be fixed since: https://github.com/Elikill58/Negativity/commit/a109086d30e0ee8bca44e140f0cc446fc97af0d5
