### ISSUE TITLE
Bungeecord Ban / Kick commands

### ISSUE THREAD

**Issue by Experical1** [Elikill58/Negativity#245]
It's about :
- [x] Other

If the server is a network, have an option in the config on the bungeecord to run the ban / kick commands from the bungeecord console instead of the spigot one, because I don't have a ban plugin on spigot, I have it on the bungeecord server.

The ban commands don't work when it runs through the spigot console because its not a spigot plugin.

**Comment by Elikill58** [comment]
Hi,
Why don't use command of ban plugin on bungee ?
Else, it's an idea, but such as you can run the command from every spigot server which have Negativity, which will do the same as if it was on bungee, it's not really important.

**Comment by Experical1** [comment]
I do have it on the bungee, I don't use litebans on the spigot servers. I already tried setting it up on all the spigot servers, but if you get banned on KitPvP, you aren't banned on the other servers even when they are all connected to the same database.

**Comment by Elikill58** [comment]
Sorry, I didn't see your message. Why don't update this issue ?

Did you finally fix it ? Use another ban system ? Stop using Negativity ?

**Comment by Elikill58** [comment]
No reply.
