### ISSUE TITLE
Vanish Feature

### ISSUE THREAD

**Issue by StormyGalaxy** [Elikill58/Negativity#253]
**It's about :**
- [x] New feature: Seeing Vanished Players

**Explain the feature that you want**
This feature will let players with a certain permission node to see a player in vanish or their head. I want this feature so I know that my staff are online, already looking at the player that a way, I can look for other people instead.

**Comment by mpfaff** [comment]
I like this feature, but I think it might best as a separate plugin. I can't think of any anti-cheat-specific code it would require, and as a separate plugin it would work with any anti-cheat.

**Comment by Elikill58** [comment]
Multiple feature are better with specific plugin, specially ban plugin for example.
For mod, I want to propose features that don't need another plugin to be great.

For me, this feature is just a bypass permission to see people even if they are vanished.

**Comment by dave9123** [comment]
OPed staff(s) can see vanished players
