### ISSUE TITLE
Air Jump - False positive while jumping

### ISSUE THREAD

**Issue by Paultje52** [Elikill58/Negativity#254]
**Describe the bug**
When bridging with any block and moving with wasd a bit while jumping gives a false positive for air jump.

**Your plugin version:** `1.9.8-fix`

**Your server version (and the software type (spigot/sponge))**
This server is running Purpur version git-Purpur-1082 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

**Proof file**
[895933a3-f98b-4bd6-9751-5673a04d632e.txt](https://github.com/Elikill58/Negativity/files/6437323/895933a3-f98b-4bd6-9751-5673a04d632e.txt)

**Screenshots**
I have a video, you can see it here.
https://user-images.githubusercontent.com/31313717/117358511-8b57cc80-aeb6-11eb-9a5e-a285b35559d1.mp4

**Additional context**
I'm also getting false flags for `Fastplace`, because I was butterfly-clicking on my right-mouse button. I don't know if it's possible to fix correctly, but that's why I'm mentioning it here and not creating a seperate issue for it

**Comment by Paultje52** [comment]
@Elikill58 If you need any help testing a possible patch, just message me on Discord: `Paultje#0933`

**Comment by Elikill58** [comment]
No problem, thanks you for report :)
