### ISSUE TITLE
Fly - False positive while shifting in vines

### ISSUE THREAD

**Issue by Paultje52** [Elikill58/Negativity#256]
**Describe the bug**
When shifting in a vine, twisting vine or weeping vine and moving around, you'll get a lot of fly flags.

**Your plugin version:** `1.9.8-fix`

**Your server version (and the software type (spigot/sponge))**
This server is running Purpur version git-Purpur-1082 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

**Proof file**
[895933a3-f98b-4bd6-9751-5673a04d632e.txt](https://github.com/Elikill58/Negativity/files/6437636/895933a3-f98b-4bd6-9751-5673a04d632e.txt)

**Screenshots**
https://user-images.githubusercontent.com/31313717/117365346-73d11180-aebf-11eb-927f-0e5df2ccbdf4.mp4

**Comment by Elikill58** [comment]
Fixed in https://github.com/Elikill58/Negativity/commit/2f03807f84bbe37f4de534f3dcbe8413f75a7e6a
