### ISSUE TITLE
False flying flag if you clime up twisting vines or weeping vines

### ISSUE THREAD

**Issue by Commandcracker** [Elikill58/Negativity#262]
I'm Running **Paper 731 MC 1.16.5** with **Negativity 1.9.8-fix**.
If you clime up **Twisting Vines or Weeping Vines** you get **flagged** and **Banned** for **Flying**.

**Comment by Elikill58** [comment]
Thanks for report, but this issue is already fix in dev build.

Concerned commit: https://github.com/Elikill58/Negativity/commit/2f03807f84bbe37f4de534f3dcbe8413f75a7e6a

(update soon, dev build available on discord)
