### ISSUE TITLE
Login message always says a new version is available (1.10) even though 1.10 is already installed

### ISSUE THREAD

**Issue by Kruize1** [Elikill58/Negativity#265]
**Describe the bug**
Keeps saying a new version is available even though I'm on the latest version

**Your plugin version**
1.10

**Your server version (and the software type (spigot/sponge))**
Paper 1.16.5

**Screenshots**
![image](https://user-images.githubusercontent.com/21042824/121760605-7c30f380-cae0-11eb-878d-82b3da4fc06c.png)

**Error / Logs**
![image](https://user-images.githubusercontent.com/21042824/121760626-9e2a7600-cae0-11eb-8509-496d4980d4db.png)

**Additional context**
Looks like the logs say i'm on 1.1 , but I have 1.10 installed. Maybe it's not counting the zero at the end of 1.10?

**Comment by Elikill58** [comment]
Yes, it was completly ignoring the 0, because 1.0 = 1
