### ISSUE TITLE
Alert messages not sync with language file.

### ISSUE THREAD

**Issue by FurryOfficial** [Elikill58/Negativity#267]
**Describe the bug**
Alert messages are not sync with language file. This bug happens in Vietnamese translation, about others i didnt checked out yet.

**Your plugin version**
1.10 (latest)

**Your server version (and the software type (spigot/sponge))**
paper 1.16.5 build #777
**Screenshots**
![image](https://user-images.githubusercontent.com/70711319/121882108-4be49180-cd3a-11eb-9db1-5d061eef5cde.png)
![image](https://user-images.githubusercontent.com/70711319/121882211-733b5e80-cd3a-11eb-86c2-e89ba14acefe.png)

**Error / Logs**
None.

**Comment by Elikill58** [comment]
Can you show me your full config ?

The showed messages are from which file ?

And warn: it's `negativity.alert` not `Negativity.alert` (it's in lower case)

**Comment by FurryOfficial** [comment]
> Can you show me your full config ?
> 
> The showed messages are from which file ?
> 
> And warn: it's `negativity.alert` not `Negativity.alert` (it's in lower case)

The config file (config.yml) or the language one ?

**Comment by Elikill58** [comment]
Both

In lower case, it works ?

**Comment by FurryOfficial** [comment]
> Both
> 
> In lower case, it works ?

Yes, it wored ;)
Thanks for your fast reply <3

**Comment by Elikill58** [comment]
Ok, no problem :)
