### ISSUE TITLE
Mysql driver deprecated warning

### ISSUE THREAD

**Issue by paj1s** [Elikill58/Negativity#269]
Loading class `com.mysql.jdbc.Driver'. This is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'. The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary.

I have bungeecord, negativity installed on the proxy and on the backend servers as well. What can i do about it? There is no driver option in config.

**Comment by RedNesto** [comment]
Hi, this is a harmless warning and you can't do anything about it. Negativity forces the MYSQL driver to load, which is triggering it.

@Elikill58 I guess we could avoid doing that and let JDBC discover the appropriate driver itself.

**Comment by Elikill58** [comment]
> @Elikill58 I guess we could avoid doing that and let JDBC discover the appropriate driver itself.

I don't know, maybe we still have to choose which one, and so load the new driver and not the old.

Just, what are your Java version and your spigot version ?

**Comment by paj1s** [comment]
Java 16 latest paper
