### ISSUE TITLE
Did I do something wrong?

### ISSUE THREAD

**Issue by aishitueruu** [Elikill58/Negativity#274]
Hi, more than anything I wanted to know if I did something wrong, configure the file where it is set that the percentage and such, but neither in the console, nor in the users with the permissions to see the alerts alerts are set. Did I do something wrong?
Maybe I missed something, I was testing the plugin with a hack client before putting it on my server and I noticed that, it does not ban or do anything that was configured.
Latest version of the plugin, paper
No screenshots in this case :(

**Comment by Elikill58** [comment]
Hi,
I'm sorry for the issue.
Do you have startup error ?

You say that people with permission don't see alert. Have you check if there is log in console ? Because alert are also log in console (by default).
The default perm to see alert is: `negativity.alert`.

Also, don't forget to enable ban feature such as explained in [wiki](https://github.com/Elikill58/Negativity/wiki) 

Can you send your config file ?

Also, you can do `/n debug <PlayerName>` to check if you can be detected, and send a fake alert just to see if everything works.

**Comment by aishitueruu** [comment]
###################################################################
#                                                                 #
#                            Negativity                           #
#                      AntiCheat by Elikill58                     #
#                                                                 #
#              If you have a problem or a suggestion,             #
#                    You can contact me on:                       #
#                  - Discord: @Elikill58#0743                     #
#       - my Discord server: https://discord.gg/KHRVTX2           #
#               - Mail: arpetzouille@gmail.com                    #
#                   - SpigotMC: Elikill58                         #
#                  - Minecraft.fr: Elikill                        #
#                                                                 #
###################################################################

# Enable cheat alerts
log_alerts: true
log_alerts_in_console: true
# if the server's Ticks Per Second drops below this value, alerts will be disabled
tps_alert_stop: 16

commands:
  # Disable or enable commands
  
  # Enable /nreport: (Alias: /report)
  report: true

  # Enable /nban: (Alias: /ban)
  ban: true
  # ^ YOU MIGHT WANT THIS ON!

  # Enable /nunban (Alias: /unban)
  unban: true
  # ^ YOU MIGHT WANT THIS ON!

  # Enable /nkick: (Alias: /kick)
  kick: true

  # Enable /nmod: (Alias: /mod)
  mod: true

  # Enable /nlang: (Alias: /lang)
  lang: true

# /report cooldown in milliseconds
# -1 to disable cooldown
time_between_report: 1000

# Alerts cooldown in milliseconds
# If the limit is bypassed, alerts will be combined:
# e.g. "exampleHacker Hit exampleUser without line of sight 5 times"
# -1 to disable cooldown
time_between_alert: 1000

# Database for storing info, if applicable
# Disabled by default
Database:
  # Enable database
  isActive: false
  # Info is stored by player ID, not username.
  # This plugin doesn't edit the database.
  # The database credentials and IP are never accessable by us.
  url: "127.0.0.1/myDb"
  user: "root"
  password: "myPassword"
  type: "mysql"

inventory:
  alerts:

    no_started_verif_cheat: false # Don't see if the player isn't analyse for this cheat

    # Don't send alerts for inactive cheats
    only_cheat_active: true

  inv_freeze_active: true

# Disable checking for cheats with certain blocks/items
items:
  # Item Name:
  # when: Set conditions
  # cheats: Which cheat(s) to disable (the id: fly, speed, antiknockback, etc.)
  #
  # Possible "when" values:
  # always : disable whenever the player has it in their hand
  # right_click : disable when the player right clicks
  # left_click : disable when the player left clicks
  # looking : disable when the player is looking at it
  # below : disable when the player is standing on it
  #
  # Disable speed and fly checking when the player is holding a compass:
  # COMPASS:
  #  when: always
  #  cheats: speed,fly

# Configuration of the permissions subsystem. For more information
# see https://github.com/Elikill58/Negativity/wiki/Permissions
Permissions:
  # The checker is used to see if a player has the correct permissions
  # By default only 'platform' is available
  # 'platform' means Negativity will use supported permissions plugins
  checker: platform

  check:
    # Open another player's inventory
    default: "negativity.check"
  showAlert:
    # See alerts
    default: "negativity.alert"
  showReport:
    # See reports from /report
    default: "negativity.seereport"
  verif:
    # Run /negativity verif
    default: "negativity.verif"
  manageCheat:
    # Manage cheats
    default: "negativity.managecheat"
  reload:
    # Reload the plugin
    default: "negativity.reload"
  report_wait:
    # Bypass report cooldown
    default: "negativity.reportwait"
  report:
    # Use /report (if enabled)
    default: "negativity.report"
  ban:
    # Use /nban (if enabled)
    default: "negativity.ban"
  unban:
    # Use /nunban (if enabled)
    default: "negativity.unban"
  mod:
    # Use /nmod (if enabled)
    default: "negativity.mod"
  lang:
    # Use /nlang (if enabled)
    default: "negativity.lang"
  max-player-by-ip:
    # Bypass the max player by IP
    default: "negativity.bypass.max-player-by-ip"
  bypass:
    # These are used to make players immune to some features
    active: false
    ban:
      # Immune to ban (auto and /nban)
      default: "negativity.bypass.ban"
    all:
      # Immune to all cheats
      default: "negativity.bypass.all"
    airplace:
      default: "negativity.bypass.airplace"
    forcefield:
      default: "negativity.bypass.forcefield"
    fastplace:
      default: "negativity.bypass.fastplace"
    speed:
      default: "negativity.bypass.speed"
    autoclick:
      default: "negativity.bypass.autoclick"
    fly:
      default: "negativity.bypass.fly"
    antipotion:
      default: "negativity.bypass.antipotion"
    fasteat:
      default: "negativity.bypass.fasteat"
    regen:
      default: "negativity.bypass.regen"
    antiknockback:
      default: "negativity.bypass.antiknockback"
    jesus:
      default: "negativity.bypass.jesus"
    nofall:
      default: "negativity.bypass.nofall"
    blink:
      default: "negativity.bypass.blink"
    spider:
      default: "negativity.bypass.spider"
    fastbow:
      default: "negativity.bypass.fastbow"
    scaffold:
      default: "negativity.bypass.scaffold"
    step:
      default: "negativity.bypass.step"
    noslowdown:
      default: "negativity.bypass.noslowdown"
    fastladder:
      default: "negativity.bypass.fastladder"
    phase:
      default: "negativity.bypass.phase"
    autosteal:
      default: "negativity.bypass.autosteal"
    nuker:
      default: "negativity.bypass.nuker"
    airjump:
      default: "negativity.bypass.airjump"
    chat:
      default: "negativity.bypass.chat"
    noweb:
      default: "negativity.bypass.noweb"
    critical:
      default: "negativity.bypass.critical"
    inventorymove:
      default: "negativity.bypass.inventorymove"
    faststairs:
      default: "negativity.bypass.faststairs"
    nopitchlimit:
      default: "negativity.bypass.nopitchlimit"
    timer:
      default: "negativity.bypass.timer"
    pingspoof:
      default: "negativity.bypass.pingspoof"

Translation:
  active: true # enable or disable per-player translation with /nlang
  lang_available:
  - ar_EG
  - cs_CZ
  - de_DE
  - en_US
  - es_ES
  - fr_FR
  - hu_HU
  - it_IT
  - nl_NL
  - no_NO
  - pl_PL
  - pt_BR
  - ro_RO
  - ru_RU
  - sq_SQ
  - sv_SV
  - vi_VN
  - zh_CN
  # Default language for players
  default: es_ES
  # The provider used to get translated messages, useful if you want to customize the way Negativity gets its messages.
  # The only one available out-of-the-box is "platform".
  provider: platform

alert:
  # Run a command when someone triggers an alert
  command:
    active: false
    # How much confidence of a cheat is needed to run command
    reliability_need: 80
    # Available placeholders:
    # %name% : Username of player who cheated
    # %uuid% : UUID of player who cheated
    # %report_type% : Type of detected cheat (either Warning or Violation)
    # %cheat_key% : Cheat ID (e.g. "nofall")
    # %cheat_name% : Cheat name (e.g. "No-Fall") : Can be changed in this config
    # %reliability% : How confident Negativity is that they are cheating
    # %warn% : Amount of warn for this cheat
    run:
    - "broadcast %name% might be using %cheat_name%!"

# Configuration of the bans subsystem. For more information,
# see https://github.com/Elikill58/Negativity/wiki/Bans
ban:
  # Enable auto-banning players
  active: true

  # Processors manage how bans are stored. Only one processor can be used at the time.
  # Available processors :
  # - file : Save bans in a folder
  # - database : Saves bans in a database. Needs a configured database (see the Database config)
  # - command : Runs another plugin's commands to ban or unban
  # - bukkit : Uses Bukkit's ban system
  # - proxy : Forwards ban execution and revocations to the proxy companion plugin.
  # You must enable bans on the proxy plugin's configuration for it to work
  #
  # The following plugins are also supported :
  # - maxbans
  # - advancedban
  # - litebans
  # - dkbans
  # Defaults to "file"
  processor: "file"

  # Commands to execute when using the "command" processor
  # You can execute as many commands as you want. Order is respected.
  #
  # Available placeholders:
  # %uuid% : uuid of banned player
  # %name% : name of banned player
  # %ip% : ip of the banned player
  # %reason% : detected cheat
  # %alert% : number of alerts for the detected cheat that triggered the ban
  # %all_alert% : all alerts for the detected cheat since you added Negativity on your server
  command:
    ban:
    - "ban %uuid% %reason% Si Quieres Apelar ve a discord, no cierres tu Mc"
    unban:
    - "unban %uuid% %reason%"
  # Cheats that aren't auto-banned for
  cheat_disabled:
  - xray
  # Confidence needed to be banned
  reliability_need: 95

  alert_need: 10
  # Formula for the length of the ban
  # IN MILLISECONDES
  time:
    # %reliability% : reliability of last alert
    # %alert% : number of alerts sent
    calculator: "43200000"
  def:
    # Minimum ban time
    ban_time: 20000
  file:
    # Log expired or revoked bans when using the "file" processor
    log_bans: true
  database:
    # Log expired or revoked bans when using the "database" processor
    log_bans: true

# Configure player specific info, like their language and alerts count.
accounts:
  storage:
    # The processor to use
    #
    # The following are available out-of-the-box:
    # - file : stored in files under ./plugins/Negativity/user/
    # - database : uses a database
    # Defaults to "file"
    id: "file"

# Verification is used to monitor cheats
verif:
  # Time to remember possible cheat events (20 ticks is usually 1 second, unless the server is lagging)
  time: 1000
  # Enables *not* alerting a player when Negativity thinks they might be cheating
  # Alerts for a specific cheat can be forcibly muted by setting "cheats.<cheat>.check_in_verif" to false
  disable_alert_on_verif: false

  storage:
    # The processor to use
    #
    # The following are available out-of-the-box:
    # - file : stored in files under ./plugins/Negativity/verif/
    # - database : uses a database
    # Defaults to "file"
    id: "file"

# Enable cheating in specific regions
region-bypass:
  enabled: false
  1:
    # WorldGuard regions to allow
    regions:
    - "spawn"
    - "wild"
    # Worlds to allow
    worlds:
    # e.g. world, world_nether, world_the_end, or any Multiverse worlds
    - "world_the_end"
    # Cheats to allow in the above regions and worlds
    cheats:
    - "fly"

# Per-cheat configuration. For more information about specific cheats
# and their detections see https://github.com/Elikill58/Negativity/wiki/Cheat
cheats:
  #
  # WARNING: An auto-checking all cheats can be create some lag on your server.
  #

  # AirPlace is when someone places a block that isn't against another (floating)
  airplace:
    # Max ping before forgiving the player
    ping: 400
    # Display name
    exact_name: "AirPlace"
    # Check for this cheat
    isActive: true
    # Send an alert if there is this chance (or more) someone is cheating
    reliability_alert: 85
    # Undo the player's action
    # See https://github.com/Elikill58/Negativity/wiki/setBack for custom options
    setBack: true
    # Kick the player from the server
    kick: true
    # Alerts sent before kicking
    alert_to_kick: 5
    # Remember the cheat when calculating things like ban duration
    check_in_verif: true

  # Forcefield is similar to KillAura - The hacker will auto-attack players near them.
  forcefield:
    # How many blocks away someone can be hit
    reach: 3.3
    # Disable spawning an invisible fake player to check for Forcefield
    ghost_disabled: true
    ping: 400
    exact_name: "Kill aura"
    isActive: true
    reliability_alert: 90
    setBack: false
    kick: false
    alert_to_kick: 5
    check_in_verif: true

  # Jesus is when a hacker walks on water like a block
  jesus:
    ping: 400
    exact_name: "Jesus"
    isActive: true
    reliability_alert: 85
    setBack: false
    kick: true
    alert_to_kick: 5
    check_in_verif: true

  # AntiPotion is when the hacker removes bad potion effects
  antipotion:
    ping: 400
    exact_name: "AntiPotion"
    isActive: true
    reliability_alert: 85
    setBack: false
    kick: false
    alert_to_kick: 5
    check_in_verif: true

  # NoFall is when the hacker disables fall damage
  nofall:
    # Kill player when confident enough
    kill: true
    kill-reliability: 98 # reliability to kill player at
    ping: 400
    exact_name: "NoFall"
    isActive: true
    reliability_alert: 80
    setBack: false
    kick: false
    alert_to_kick: 5
    check_in_verif: true

  # FastEat is to eat something instantly
  fasteat:
    ping: 400
    exact_name: "FastEat"
    isActive: true
    reliability_alert: 85
    setBack: false
    kick: true
    alert_to_kick: 5
    check_in_verif: true

  # FastPlace places blocks quicker than normal
  fastplace:
    ping: 400
    exact_name: "FastPlace"
    isActive: true
    # Minimum time between block places,
    # in milliseconds
    time_2_place: 50
    reliability_alert: 80
    setBack: true
    kick: true
    alert_to_kick: 5
    check_in_verif: true

  # Speed hacks makes you run faster
  speed:
    ping: 400
    exact_name: "Speed"
    isActive: true
    reliability_alert: 90
    setBack: true
    kick: true
    alert_to_kick: 6
    check_in_verif: true

  # AutoClick makes you automatically click, very fast
  autoclick:
    click_alert: 15
    ping: 400
    exact_name: "AutoClick"
    isActive: true
    reliability_alert: 90
    setBack: true
    kick: false
    alert_to_kick: 5
    check_in_verif: true

  # Fly lets a hacker fly like in Creative Mode
  fly:
    ping: 400
    exact_name: "Fly"
    isActive: true
    reliability_alert: 90
    setBack: true
    kick: true
    alert_to_kick: 5
    check_in_verif: true

  # Regen regenerates a hacker's health very quickly
  regen:
    ping: 400
    exact_name: "Regen"
    isActive: true
    reliability_alert: 95
    setBack: false
    kick: false
    alert_to_kick: 5
    check_in_verif: true

  # AntiKnockback removes the knockback effect for a hacker
  antiknockback:
    ping: 400
    exact_name: "AntiKnockback"
    isActive: true
    reliability_alert: 90
    setBack: true
    kick: false
    alert_to_kick: 5
    check_in_verif: true
    # Configuration to prevent false flagging. Set to false to prevent all possible incidents
    algo: "(0.00000008 * velY * velY) + (0.0001 * velY) - 0.0219"

  # Blink enables a hacker to teleport by simulating low ping (i.e. lag)
  blink:
    ping: 400
    exact_name: "Blink"
    isActive: true
    reliability_alert: 90
    setBack: true
    kick: false
    alert_to_kick: 5
    check_in_verif: true

  # FastBow shoots a bow quicker than normal
  fastbow:
    ping: 400
    exact_name: "FastBow"
    isActive: true
    reliability_alert: 80
    setBack: true
    kick: false
    alert_to_kick: 5
    check_in_verif: true

  # Spider allows hackers to climb all walls like a ladder
  spider:
    ping: 400
    exact_name: "Spider"
    isActive: true
    reliability_alert: 85
    setBack: true
    kick: true
    alert_to_kick: 5
    check_in_verif: true

  # Sneak allows a hacker to sneak, but with normal walking speeds
  sneak:
    ping: 400
    exact_name: "Sneak"
    isActive: true
    reliability_alert: 90
    setBack: true
    kick: false
    alert_to_kick: 5
    check_in_verif: true

  # Scaffold places a block under you without you having to look
  scaffold:
    ping: 400
    exact_name: "Scaffold"
    isActive: true
    reliability_alert: 90
    setBack: true
    kick: false
    alert_to_kick: 5
    check_in_verif: true

  # Step allows a hacker to jump twice as high
  step:
    ping: 400
    exact_name: "Step"
    isActive: true
    reliability_alert: 95
    setBack: true
    kick: true
    alert_to_kick: 5
    check_in_verif: true

  # NoSlowDown remove slow down effects (like with soul sand)
  noslowdown:
    ping: 400
    exact_name: "NoSlowDown"
    isActive: true
    reliability_alert: 98
    setBack: false
    kick: true
    alert_to_kick: 6
    check_in_verif: true

  # FastLadders lets a hacker climb ladders very quickly
  fastladder:
    ping: 400
    exact_name: "FastLadder"
    isActive: true
    reliability_alert: 90
    setBack: true
    kick: true
    alert_to_kick: 5
    check_in_verif: true

  # Phase lets a hacker glitch through a block
  phase:
    ping: 400
    exact_name: "Phase"
    isActive: true
    reliability_alert: 90
    setBack: true
    kick: true
    alert_to_kick: 5
    check_in_verif: true

  # AutoSteal lets a hacker take items from someone
  autosteal:
    ping: 400
    exact_name: "AutoSteal"
    isActive: true
    reliability_alert: 85
    setBack: true
    kick: true
    alert_to_kick: 5
    check_in_verif: true

  # XRay is when you can see ores through walls - detected by ore mined per minute
  xray:
    ping: 400
    exact_name: "XRay"
    isActive: true
    reliability_alert: 98
    setBack: true
    kick: false
    alert_to_kick: 5
    check_in_verif: true

  # Nuker/BedBreaker automatically breaks blocks near a hacker
  nuker:
    ping: 400
    exact_name: "Nuker"
    isActive: true
    reliability_alert: 95
    setBack: true
    kick: true
    alert_to_kick: 5
    check_in_verif: true

  # AirJump lets you double jump, triple jump, etc.
  airjump:
    ping: 400
    exact_name: "AirJump"
    isActive: true
    reliability_alert: 85
    setBack: true
    kick: true
    alert_to_kick: 5
    check_in_verif: true

  # Chat is insults (i.e. swearing) and spamming
  chat:
    ping: 400
    exact_name: "Chat"
    isActive: false
    reliability_alert: 60
    setBack: false
    kick: false
    alert_to_kick: 5
    check_in_verif: true
    insults:
    - "ajsldkjsalnasnm"
    - "askdas"
    - "asdkljsan"

  # NoWeb removes low speed from cobwebs
  noweb:
    ping: 400
    exact_name: "NoWeb"
    isActive: true
    reliability_alert: 90
    setBack: true
    kick: false
    alert_to_kick: 5
    check_in_verif: true

  # Critical makes all of your attacks critical hits (even while sneaking)
  critical:
    ping: 400
    exact_name: "Critical"
    isActive: true
    reliability_alert: 90
    setBack: false
    kick: false
    alert_to_kick: 5
    check_in_verif: true

  # InventoryMove lets you walk and edit your inventory at the same time
  inventorymove:
    ping: 400
    exact_name: "InventoryMove"
    isActive: true
    reliability_alert: 97
    setBack: false
    kick: false
    alert_to_kick: 5
    check_in_verif: true

  # FastStairs let you walk faster on stairs
  faststairs:
    ping: 400
    exact_name: "FastStairs"
    isActive: true
    reliability_alert: 90
    setBack: false
    kick: true
    alert_to_kick: 7
    check_in_verif: true

  # NoPitchLimit enabled hackers to see behind themselves
  nopitchlimit:
    ping: 400
    exact_name: "NoPitchLimit"
    isActive: false
    reliability_alert: 60
    setBack: false
    kick: false
    alert_to_kick: 5
    check_in_verif: true

  # Timer makes the player game's go faster
  timer:
    ping: 400
    exact_name: "Timer"
    isActive: true
    reliability_alert: 90
    setBack: false
    kick: false
    alert_to_kick: 7
    check_in_verif: true
    max_variation: 7

  # PingSpoof fakes the ping of the player to trick the anti-cheat
  pingspoof:
    ping: 100000
    exact_name: "PingSpoof"
    isActive: true
    reliability_alert: 98
    setBack: false
    kick: true
    alert_to_kick: 5
    check_in_verif: true

  # These are some special features
  special:
    # Kick fake accounts
    mcleaks:
      kick: true
    # Server Crash is when someone is trying to crash the server
    server_crash:
      name: "Server Crasher"
      kick: false
      ban: false
      # The time of the ban, in milliseconds.
      # Default: 2629800000 (1 month)
      ban_time: 2629800000
    # Invalid Name is when someone trys to crash other players by setting an invalid username
    invalid_name:
      name: "Invalid Name"
      kick: false
      ban: false
      # The time of the ban, in milliseconds.
      # Default: -1 (definitive)
      ban_time: -1
    # Max player by IP sets a limit to how many plays can connect from the same IP (i.e. internet router or house)
    max-player-by-ip:
      name: "Max Player/IP"
      # number of maximum allowed player on the same IP
      # default: 4. It means that the third people will be kicked.
      number: 2
      # You can config perm at the top of this config
      perm-bypass-enabled: false
stats: true

**Comment by aishitueruu** [comment]
I'm new to this, so I should send it? sorry if I made a mistake :c
I thought the alerts would appear in the console, that's why I logged in with only one user, but I did make sure to give permissions to the staff :c

**Comment by aishitueruu** [comment]
https://anonfiles.com/j6Z3s240ub/config_yml
encontré de esa forma mejor :,0

**Comment by Elikill58** [comment]
> I'm new to this, so I should send it? sorry if I made a mistake :c
> I thought the alerts would appear in the console, that's why I logged in with only one user, but I did make sure to give permissions to the staff :c

You can format it with 3 ` before and after message, such as Discord. It's a markdown feature.

It seems good. So for me, there is few things that can don't show alert:
- Check your ping. By default, over 200ms your not detected.
- Don't be on creative, because lot of check are not working.
- Use different hack such as Fly, Nofall or Spider because those check works great.

**Comment by aishitueruu** [comment]
![console](https://user-images.githubusercontent.com/82283123/124366578-695c9b00-dc16-11eb-8b6f-f67ab709b5f0.png)
Hello again, I was reading a little bit the plugin configuration and I didn't put anything wrong :c
Well the point is that I tested the plugin only on a spigot 1.17 server thinking that maybe there was a problem with another plugin I had but this appeared in the console
Do you think it is because it is a free host? As I told you before, I am configuring everything to just buy the host and just copy everything. I didn't make any changes in the plugin configuration, it is as it comes from vanilla. I would appreciate if you could help me :c 
It does not recognize any alert in the console

**Comment by Elikill58** [comment]
Hi,
I'm sorry for the late, I'm not at home this week-end. For faster support, come on discord.

For the issue on your screen, I will fix it. But it's completly different than your current one which is: you don't see alert.

Did you tried with default config ?
Also, what is the result of the debug command ?

**Comment by aishitueruu** [comment]
> Hi,
> I'm sorry for the issue.
> Do you have startup error ?
> 
> You say that people with permission don't see alert. Have you check if there is log in console ? Because alert are also log in console (by default).
> The default perm to see alert is: `negativity.alert`.
> 
> Also, don't forget to enable ban feature such as explained in [wiki](https://github.com/Elikill58/Negativity/wiki)
> 
> Can you send your config file ?
> 
> Also, you can do `/n debug <PlayerName>` to check if you can be detected, and send a fake alert just to see if everything works.

**Comment by aishitueruu** [comment]
I closed it by accident. Well the point is that after performing the command nothing appears neither in the console nor in the game.
I already sent you a request to discord
leonardo_lpm

**Comment by Elikill58** [comment]
Ok that's what I was thinking because you didn't write any message ...

So I just reopen it.
Ok, let's continue on discord !

**Comment by Elikill58** [comment]
After discussion is discord, it works:
![image](https://user-images.githubusercontent.com/17381066/125250085-26758400-e2f6-11eb-9277-6ffcccde2f23.png)

I close this issue.
