### ISSUE TITLE
GH Actions for testing & building v2

### ISSUE THREAD

**Issue by RedNesto** [Elikill58/Negativity#275]
- [x] automate Spigot JARs setup with BuildTools via custom Gradle tasks
- [ ] setup a workflow for running tests
- [ ] setup a workflow for publishing releases (publication endpoint TBD)

**Comment by dave9123** [comment]
I don't think it's possible for testing.

**Comment by Elikill58** [comment]
> I don't think it's possible for testing.

It will need lot of work, but how v2 is made allow it IMO

**Comment by Elikill58** [comment]
Abandonned feature - Not planned
