### ISSUE TITLE
Possible duplications or other game breaking issues could exist on Sponge

### ISSUE THREAD

**Issue by FunkyNico** [Elikill58/Negativity#288]
**Describe the bug**
Possible duplications or other game breaking issues could exist.

**Your plugin version**
1.11.

**Your server version (and the software type (spigot/sponge))**
    Minecraft: 1.12.2
    SpongeAPI: 7.4.0-500a60a87
    Sponge: 1.12.2-7.4.3
    SpongeForge: 1.12.2-2838-7.4.3
    Minecraft Forge: 14.23.5.2860
    JVM: 1.8.0_312/64-bit (Oracle Corporation)
    OS: Linux (4.15.0-141-generic/amd64)

**Error / Logs**
https://mclo.gs/fHJcwE6

**Additional context**
When i startup the server i see this message, before i was using the lastest version on Ore Repository for Sponge, but i updated to the lastest version on Spigot.
I'm using PacketGate from this https://github.com/CrushedPixel/PacketGate/issues/11 (0.12) because the latest published version on releases is 0.11.

**Comment by Elikill58** [comment]
This should be fixed with https://github.com/Elikill58/Negativity/commit/15411ae9374facfb5cb13bd845e69d6cb9d10cc0
