### ISSUE TITLE
Error with the Scheduler of Sponge

### ISSUE THREAD

**Issue by FunkyNico** [Elikill58/Negativity#289]
**Describe the bug**
Error with the Scheduler of Sponge.

**Your plugin version**
1.11.

**Your server version (and the software type (spigot/sponge))**
Minecraft: 1.12.2
SpongeAPI: 7.4.0-500a60a87
Sponge: 1.12.2-7.4.3
SpongeForge: 1.12.2-2838-7.4.3
Minecraft Forge: 14.23.5.2860
JVM: 1.8.0_312/64-bit (Oracle Corporation)
OS: Linux (4.15.0-141-generic/amd64)

**Error / Logs**
https://mclo.gs/u1Dr2Ij

**Additional context**
After the server finish to startup i see this message various times and keep going until the server is stopped.

**Comment by Elikill58** [comment]
It seems to be linked with #288 because it's an error with Metrics. Can you share full log ?

**Comment by FunkyNico** [comment]
> It seems to be linked with #288 because it's an error with Metrics. Can you share full log ?

Full log: https://mclo.gs/zTImhkD

Mods (86): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, AI Improvements, AppleSkin, Applied Energistics 2, Aquaculture, Artifacts, Attribute Fix, AutoRegLib, Baubles, Better Animals Plus, Better Diving, BiomeTweaker, Biomes O' Plenty, Bookshelf, Carry On, Chameleon, Chisel, CoFH Core, CoFH World, CodeChicken Lib, Comforts, CommonCapabilities, CreativeCore, CreativeCoreDummy, Cyclops Core, Doggy Talents, DupeFix Project, Fast Leaf Decay, FastFurnace, FastWorkbench, FoamFix, FoamFixCore, Ice and Fire, Immersive Engineering, Improved Backpacks, Iron Chest, IvToolkit, Just Enough Items, JustEnoughIDs, LLibrary, LibraryEx, Minecraft Comes Alive, Mowzie's Mobs, MrCrayfish's Furniture Mod, NetherEx, NetherPortalFix, No Mob Spawning on Trees, Pam's HarvestCraft, Placebo, Player Revive, ProjectE, Quark, Quark Oddities, RandomPatches, Recurrent Complex, Redstone Flux, SecurityCraft, Serene Seasons, SpongeForge, Storage Drawers, Surge, SwingThroughGrass, Thaumcraft, The Twilight Forest, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Thermal Innovation, Tiquality, TorchMaster, UniDict, Unloader, VanillaFix, Waila, Wall-Jump!, WanionLib, What Are We Looking At, Wither Skeleton Tweaks, YUNG's Better Caves, Yet Another Recipe Conflict Fixer, performant Mod.

Plugins (27): Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge, Altimeter, Cosmos, DupeFixer, FoxCore-Sponge, FoxGuard-Sponge, Inventory Access, ItemChat, LangSwitch, LuckPerms, MMCRestrict, Mega Menus, Mirage, Negativity, Nucleus, PacketGate, SafeTrade, Sledgehammer, SleepVote, TooMuchStock, Total Economy, VillagerShops, WorldEdit, spark.

**Comment by Elikill58** [comment]
Thanks ! It seems to be an error with Metrics that not fully load. I will check it.

**Comment by Elikill58** [comment]
This should be fixed with https://github.com/Elikill58/Negativity/commit/15411ae9374facfb5cb13bd845e69d6cb9d10cc0
