### ISSUE TITLE
Bansystem support

### ISSUE THREAD

**Issue by Black-Desire** [Elikill58/Negativity#290]
**It's about :**
- [ ] A new plugin support

**Explain the feature that you want**
I would like to have Support for DKBANS [https://www.spigotmc.org/resources/dkbans-v5-bansystem-player-management-punishment-templates-mysql-h2-bukkit-bungeecord.52570/] because its a really good system
and with auto bans in it, it would be perfect because of alt manager etc.

**Comment by Elikill58** [comment]
This is already done.
More informations on [wiki](https://github.com/Elikill58/Negativity/wiki/Bans#dkbans)
