### ISSUE TITLE
Banning bad names

### ISSUE THREAD

**Issue by Deeptanil** [Elikill58/Negativity#295]
Just like invalid name, i don't want people with curse words or banned words in their names. So they would get banned upon join.
Since you have invalid name... I think it'll be appropriate to have banned_names (or something)
There can be a list (preferably in a different yml) that lists the banned words.

**Comment by Deeptanil** [comment]
Can y'all add it to the free version 👉👈;-;

**Comment by Elikill58** [comment]
> Can y'all add it to the free version 👉👈;-;

It's on both versions. If you check commit, you can see there is 2 which is linked to this issue, one per version.

**Comment by Deeptanil** [comment]
No new update on spigot?

**Comment by Elikill58** [comment]
Not yet, I will fix other things. I don't make update for all New features. I can send you dev build if you want

**Comment by Deeptanil** [comment]
Sure that'll be nice
