### ISSUE TITLE
Translation additional stuff

### ISSUE THREAD

**Issue by dave9123** [Elikill58/Negativity#296]
**It's about :**
- [x] A translation
- [ ] A new plugin support
- [ ] New detection
- [ ] Other

**Explain the feature that you want**
So people from other country (that doesn't know English well) can understand easily. Like there's stuff possible to help improve the language with/without using Github.

**Additional context**
Like there is more language choices for easier understanding for people who doesn't really understand English.

Pardon me for my bad English

**Comment by Elikill58** [comment]
I don't understand. What do you want to translate ? You can already change the lang

**Comment by Elikill58** [comment]
Please add more details. If you are just asking for an easier way to manage language, one is already in work in progress.

**Comment by dave9123** [comment]
Oh ok
