### ISSUE TITLE
Make the chat hack better

### ISSUE THREAD

**Issue by dave9123** [Elikill58/Negativity#297]
**It's about :**
- [ ] A translation
- [ ] A new plugin support
- [ ] New detection
- [x] Other

**Explain the feature that you want**
Some people are frustrated from toxic chat so hopefully make it better. You can get a cuss/bad word(s) from API or list in/outside the plugin.

**Additional context**
From any API or list that had bad word(s). [zacanger/profane-words](https://github.com/zacanger/profane-words)

**Comment by Elikill58** [comment]
The default config should be upgraded but there already is this feature here: https://github.com/Elikill58/Negativity/blob/master/config.yml#L665
