### ISSUE TITLE
Bypass with Rise Client - NoSlowDown

### ISSUE THREAD

**Issue by dejwideek-dev** [Elikill58/Negativity#302]
**Modes:**
- [x] vanilla (slowdown: 50)
- [x] intave (slowdown: 50)
- [x] delay (slowdown: 50)
- [x] hypixel (slowdown: 50)
- [x] reverse ncp (slowdown: 50)
- [x] ncp (slowdown: 50)

**Comment by Elikill58** [comment]
Fixed and with slowdown 50 it doesn't give advantage (but can flag speed)
