### ISSUE TITLE
Bypass with Rise Client - Phase

### ISSUE THREAD

**Issue by dejwideek-dev** [Elikill58/Negativity#308]
**Modes:**
- [ ] vanilla (fly speed: 0.2, if you suffocate in block (for example: anvil fall))
- [ ] sand (fly speed: 0.2, if you suffocate in sand)
- [ ] normal (sometimes, with jump)

**Comment by Elikill58** [comment]
Sorry but phase cheat just make easier the way to be bugged into bug, but the actual Phase cheat is more probable that it will be removed than be upgraded
