### ISSUE TITLE
console error on 1.7.10

### ISSUE THREAD

**Issue by coolpvpv1** [Elikill58/Negativity#32]
Describe the bug
when you load negativity and join the server it gives you a error on 1.7.10-

Your plugin version
The version of Negativity that you are using 1.4

Your platform version (and precise the platforme (spigot/sponge))
The version of your server spigot 1.7.10

Screenshots
not needed

Error / Logs
If applicable, add logs of error (copy/paste on pastebin/hastebin).
https://paste.ubuntu.com/p/kT63tM3mBY/
Additional context
not needed

**Comment by Elikill58** [comment]
Hello,
Thanks for report, it's fixed on latest commit. To get the fixed version, download the plugin here: https://dl.eliapp.fr/Negativity.jar .
