### ISSUE TITLE
[Bug] Error on console

### ISSUE THREAD

**Issue by PhoenixCodingStuff** [Elikill58/Negativity#328]
### Which platform are you using ?

Paper

### Versions of Negativity and of the server

Plugin version is - 1.12.1
Paper - git-Paper-64 (MC: 1.19)

### Step to reproduce

Uh don't know tbh , appears randomly

### Errors / Logs

https://paste.walshy.dev/ptthtgKUvKkE

**Comment by Elikill58** [comment]
This is already fixed in dev build since https://github.com/Elikill58/Negativity/commit/28d7bc2875c3abb96392d17e9fa6b5b0b767fc2a
