### ISSUE TITLE
[Bug] player kick Event Fails (kick java.lang.Throwable: null)

### ISSUE THREAD

**Issue by Spielepapagei** [Elikill58/Negativity#329]
### Which platform are you using ?

Paper, Velocity

### Versions of Negativity and of the server

My version is: 2.4.2

3 Servers 1.19 with paper version #77
Velocity 1.19 Version #162 from papermc.io

### Step to reproduce

Default setup, noting else. 
I Think

### Errors / Logs

https://gist.github.com/Spielepapagei/2549026a4f64b5a22faa907cf225538a

**Comment by Elikill58** [comment]
You seems to use v1.12.1. You put the wrong version, or the wrong log ?

**Comment by Spielepapagei** [comment]
You put the wrong version?
 Can you explain

**Comment by Elikill58** [comment]
Yes, you said your version of Negativity is 2.4.2, but from the log that you send, I can say you are with free version (so 1.x). So, I think you are on 1.12.1

**Comment by Spielepapagei** [comment]
Oh okay, this mean the new versions above 1.12.2 are only paid?
This includes support for 1.19?

**Comment by Elikill58** [comment]
Free and premium have 1.19 support.
All 2.x are paid. All 1.x are free. I will release 1.12.2, 1.13 etc. You can download and build yourself yes.

**Comment by Spielepapagei** [comment]
Thanks :D
