### ISSUE TITLE
Bypass for all fly checks

### ISSUE THREAD

**Issue by jonesdevelopment** [Elikill58/Negativity#331]
### Which platform are you using ?

Spigot

### Versions of Negativity and of the server

My version is: latest Negativity on a 1.8.8 Spigot server
https://media.discordapp.net/attachments/896568458559500289/1004032813076590713/unknown.png

### What were you doing while finding bypass ?

Testing the anti cheat using my client
https://www.youtube.com/watch?v=I6StP2axCj0

### Which client with which mode ?

Spoofing your ground state to true will bypass all Fly checks if you aren't flying too fast

Code for the Fly:
```
if (mathGround()) {
    mc.thePlayer.motionY = 0;
}

if (++ticks > 5) ticks = 0;

mc.timer.timerSpeed = Math.max(Math.min(ticks, 1.1f), 1);

strafe(mc.thePlayer.getAIMoveSpeed() * Math.max(ticks, 3.5));

event.getLocation().setGround(true);
```

**Comment by Elikill58** [comment]
Thanks for this bypass, I will see if it appear for v2 too. Just, don't forget to update your 1.8.8 server ...

**Comment by jonesdevelopment** [comment]
I know that you aren't the owner of this video. But from seeing the current state of the combat checks and the videos out there, that "test" your anti cheat, I thought it's good to mention that you should test your checks with better clients, also premium ones.

**Comment by Elikill58** [comment]
Can you give more details about which event, and in which client did you put this new module ? I failed to reproduce a working bypass

**Comment by jonesdevelopment** [comment]
It's my own client;

> onUpdateWalkingPlayer() EntityPlayerSP.java:
![image](https://user-images.githubusercontent.com/73846784/186400344-a7ceaf70-d93f-428b-a481-6a2a25c0da76.png)

> Listen EventMotion:
![image](https://user-images.githubusercontent.com/73846784/186400417-f71d1091-0a23-4018-ab9d-772f92a303b5.png)

If you want more information or want to test with that client you can contact me on Discord: Jones#3279
