### ISSUE TITLE
[FP]: Fly false flag for bedrock users

### ISSUE THREAD

**Issue by jonathan-up** [Elikill58/Negativity#339]
### Which platform are you using ?

Paper

### Versions of Negativity and of the server

My version is: spigot: 1.19_R1. Negativity: 2.5

### How did you made the false flag ?

Step 1: 使用Geyser和floodgate让基岩版进入服务器
Step 2: 基岩版玩家在跳上方块的时候可能会提示fly作弊

Some times, bedrock player may kicked by Negativity for fly cheat, and I use geyser and floodagte to let bedrock player join my server.

### Can you show the proof file ?

My proof file: 太多文件在那个目录下

**Comment by Elikill58** [comment]
Thanks for report, but I'm not chinese. Can you translate it into english ?

**Comment by jonathan-up** [comment]
ok, wait a minutes

**Comment by jonathan-up** [comment]
Some times, bedrock player may kicked by Negativity for fly cheat, and I use geyser and floodagte to let bedrock player join my server

**Comment by Elikill58** [comment]
Translate in #340
