### ISSUE TITLE
console error when flagging checks?

### ISSUE THREAD

**Issue by coolpvpv1** [Elikill58/Negativity#34]
Describe the bug
i was just testing the ac flying around setting off some checks then i look in console and see some errors

Your plugin version
The version of Negativity that you are using 1.4

Your platform version (and precise the platforme (spigot/sponge))
The version of your server spigot 1.8.8

Screenshots
none

Error / Logs
If applicable, add logs of error (copy/paste on pastebin/hastebin).
https://paste.ubuntu.com/p/yvSnYnWvMr/
Additional context
none

**Comment by RedNesto** [comment]
This issue is fixed in the next version (by https://github.com/Elikill58/Negativity/commit/d46ab4cdf46179139157f89db32a6c328a71336d).
