### ISSUE TITLE
[FP]: Jesus false flag

### ISSUE THREAD

**Issue by jonathan-up** [Elikill58/Negativity#341]
### Which platform are you using ?

Paper

### Versions of Negativity and of the server

My version is: spigot: W1-.19_F1. Megatiuity:2.5

### How did you made the false flag ?

Players walk too close to water will trigger cheating, Usually players get cheating easily in Marsh terrain

### Can you show the proof file ?

My proof file:

**Comment by Elikill58** [comment]
Should be fixed with https://github.com/Elikill58/Negativity/commit/96c2c47b8afa1f82c65278d033362a99ed5fae50. Can reproduce with it.
