### ISSUE TITLE
[FP]: GroundSpoof check-blocks-under broken on Minestom

### ISSUE THREAD

**Issue by CamperSamu** [Elikill58/Negativity#353]
### Which platform are you using ?

Other

### Versions of Negativity and of the server

My version is: Minestom w/[MinestomLauncher](https://github.com/CampHQmc/MinestomLauncher) & [MinestomPvP](https://github.com/CampHQmc/MinestomPvP), Negativity v2 compiled, commit [09db2ae](https://github.com/Elikill58/Negativity/commit/09db2ae51efea80948ad8a7c94d29884f930668d)

### How did you made the false flag ?

Step 1: Boot up a Minestom Server with Negativity and a Minecraft Client (I logget with Meteor but it FP'd with Vanilla too)
Step 2: Jump

### Can you show the proof file ?

My proof file: 
[69b72d6f-ae64-493d-add8-db18b3b8b9c2.zip](https://github.com/Elikill58/Negativity/files/10522630/69b72d6f-ae64-493d-add8-db18b3b8b9c2.zip)

**Comment by Elikill58** [comment]
Seems to be fixed since
