### ISSUE TITLE
[Bug] %alert% in the bans.yml doesn't work

### ISSUE THREAD

**Issue by Josh65-2201** [Elikill58/Negativity#357]
### Which platform are you using ?

Paper

### Versions of Negativity and of the server

My version is: 2.6.1

When I put %alert% as it says in the file it doesn't actually parses and just shows as %alert% on the ban message.

### Step to reproduce

1. Enable command as the ban processor
2. Run Minecraft's normal ban command with %alert% as part of the reason message
3. Get banned
4. See message shows %alert% rather than the value

**Comment by Elikill58** [comment]
I don't see where there is alert placeholder : https://github.com/Elikill58/Negativity/blob/v2/common/resources/assets/negativity/config.yml#L512

**Comment by Elikill58** [comment]
Oh ok. Sorry I through you were talking about webhooks. For the command, it's because there is no related cheat. Which value should be put ?

**Comment by Josh65-2201** [comment]
No quite sure what you're asking. If it's the ban command I use "ban %name% Detected %reason% %alert%"

**Comment by Elikill58** [comment]
The comment on the file say that `%alert%` is the value about amount of alert for the cheat that **triggered** the ban. So, when running the command by yourself, there is no cheat that trigger it

**Comment by Josh65-2201** [comment]
So is it not supposed to work? With the way it's said in the file I thought it would show (`cheat name` x`how many times`, `another cheat name` x`how many times`,)

**Comment by Elikill58** [comment]
Yes but they are alerts amounts for each cheat. And so, which one should be selected? that's the issue, and yes it's the supposed behavior that I didn't think about it
