### ISSUE TITLE
[Bug] Bedrock (using geyser) spams unable to read packet error when looking around

### ISSUE THREAD

**Issue by Josh65-2201** [Elikill58/Negativity#359]
### Which platform are you using ?

Paper

### Versions of Negativity and of the server

My version is: 2.6.1

I have only gotten this when looking around. Doesn't cause any issue on the client side.

### Step to reproduce

1. Connect any bedrock client with Geyser to the server
2. Look around

### Errors / Logs

[23:43:31 WARN]: [Negativity] Failed to read packet with ID 19 (POSITION) to B-Josh652956 (CLIENT_TO_SERVER - decode - 1.19.3)

**Comment by Elikill58** [comment]
What is your server version ? 1.19.3 ?

**Comment by Josh65-2201** [comment]
1.18.2

**Comment by Elikill58** [comment]
Is that fixed now?

**Comment by Josh65-2201** [comment]
Seems so
