### ISSUE TITLE
[Bug] ProtocolLib incompatibly

### ISSUE THREAD

**Issue by Josh65-2201** [Elikill58/Negativity#361]
### Which platform are you using ?

Paper

### Versions of Negativity and of the server

My version is: 2.6.1
Protocol Lib: 4.8

Negativity loads but won't detect anything done by players removing Protocol Lib fixes this.
Was mentioned on discord but I'm putting this here so it can be tracked more easily and updates can be given.

### Step to reproduce

1. Install negativity 2.6.1
2. Install Protocol Lib 4.8
3. See negativity doesn't detect anything done by players

**Comment by Elikill58** [comment]
Is the same with ProtocolLib 5.0.0, and without ? (as there isn't error, I want to be sure it's because of PL)

**Comment by Josh65-2201** [comment]
Where is v5? I can only find 4.8. There no errors in console and negativity loads but doesn't do anything. I remove only Protocol Lib and it started working.

**Comment by Elikill58** [comment]
Dev build of ProtocolLib are here: https://ci.dmulloy2.net/job/ProtocolLib/

**Comment by Josh65-2201** [comment]
V5 so far is working with negativity

**Comment by Elikill58** [comment]
Ok so maybe we could close this issue, or should I add a message for others users (in console) ?

**Comment by Josh65-2201** [comment]
Can add a message if you like but doesn't seem to be worth it as I don't think it would come up often.
