### ISSUE TITLE
[Bug] Sometimes the server stops responding and crashes when a player joins/kicked

### ISSUE THREAD

**Issue by Josh65-2201** [Elikill58/Negativity#362]
### Which platform are you using ?

Paper

### Versions of Negativity and of the server

My version is: 2.6.1

Doesn't happen all the time but I've had it often enough with just me it would be an issue with more people.

### Step to reproduce

1. Join the server

### Errors / Logs

[2023-03-24-7.log](https://github.com/Elikill58/Negativity/files/11058900/2023-03-24-7.log)

**Comment by Draghonir** [comment]
Hi ;) I've already sent it to you on discord but I'm putting it here so that you can group everything

https://haste.zendrique.fr/ifoqoyixen.yaml

https://haste.zendrique.fr/oniyunecof.yaml

**Comment by Elikill58** [comment]
Yes, it's the same error. I've seen with RedNesto to find a way to fix it
