### ISSUE TITLE
Internal Exception build : Fix#363  24/03/202 10:06 am

### ISSUE THREAD

**Issue by Draghonir** [Elikill58/Negativity#364]
### Which platform are you using ?

Paper

### Versions of Negativity and of the server

Hi

My version is: 2.6.1 Premium

"When I connect to the server, after 10 seconds I get kicked out. I reverted to the build of March 19, 2023 and the problem was gone. There is no message in the console, just this message when I get kicked

### Step to reproduce

connect to the server, and wait10 seconds for get kicked out

<img width="1920" alt="vd" src="https://user-images.githubusercontent.com/107469643/227503469-192e6a28-a730-4f48-8cea-fe656fd2a0ea.png">

**Comment by Elikill58** [comment]
Please use older build as explained here: https://discord.com/channels/361214329158238218/787349365438021632/1087872720894709830. It's not fixed yet
