### ISSUE TITLE
[Bug]  Task #77867 for Negativity v2.6.1-SNAPSHOT generated an exception

### ISSUE THREAD

**Issue by Draghonir** [Elikill58/Negativity#365]
### Versions of Negativity and of the server

[My version is 2.6.1

Hi

The console is spamming this error message, https://haste.zendrique.fr/iwemeyelif.properties causing the CPU usage to skyrocket and making it impossible to play properly. 

The server is very unstable due to error #362 in I and it shuts down randomly very frequently when there are more than 7 active players.

 

### Step to reproduce

Nothing, only crash random

**Comment by Elikill58** [comment]
One player seems to have a corrupted file. You can remove the user folder to quickly fix the issue, I will change something in my side.
You can also use a database instead of files (I can help you with this).

**Comment by Draghonir** [comment]
Im gonna delete all user proof

**Comment by Elikill58** [comment]
Do it with user too, not only `plugins/Negativity/user/proof`

**Comment by Elikill58** [comment]
Fixed since https://github.com/Elikill58/Negativity/commit/d08c5a6ee50fd8c59f2f48934f4c44b1c84eb200
