### ISSUE TITLE
[FP]: Fast place is too sensitive

### ISSUE THREAD

**Issue by Josh65-2201** [Elikill58/Negativity#369]
### Which platform are you using ?

Paper

### Versions of Negativity and of the server

My version is: 2.6.1

When I use Minecraft normal place speed in survival or creative it will trigger the fast place cheat.

### How did you made the false flag ?

1. Enter creative or survival
2. Get a stack of blocks
3. Hold or spam click place blocks

### Can you show the proof file ?

My proof file:
[9aad764c-03e9-4c01-8336-0931d153c67e.txt](https://github.com/Elikill58/Negativity/files/11158183/9aad764c-03e9-4c01-8336-0931d153c67e.txt)

**Comment by Elikill58** [comment]
If you have latest dev build, you can check for latest options [here](https://github.com/Elikill58/Negativity/blob/v2/common/resources/modules/fastplace.yml#L40). Make then lower and it could be fibe

**Comment by Josh65-2201** [comment]
What's the difference between `median` and `time_ticks`?

**Comment by Elikill58** [comment]
Median is no longer used, it's a typo. It seems I forgot to remove it

**Comment by Josh65-2201** [comment]
Ok not sure why but it seem to be working now.
