### ISSUE TITLE
Kick Notifications in Chat game

### ISSUE THREAD

**Issue by Draghonir** [Elikill58/Negativity#377]
### What is concerned ?

Options in feature

### Are you using v2 (premium, 8€) ?

- [X] Yes I bought Negativity V2

### What is your idea ? What do you want ?

Hi, I would like to add kick logs to the in-game chat, for example:

[negativity] %player% has been kicked for fly.

The kick alerts are currently displayed in the logs, but I think it would be great to have them added to the in-game chat for the operators."

I hope this helps! Let me know if you have any further questions.

**Comment by Josh65-2201** [comment]
You can. Add `negativity.alert` to the players in your permission manager

**Comment by Elikill58** [comment]
He means, a notification when someone is kicked not onyl when there is alert
