### ISSUE TITLE
[FP]: Flagged for fly in creative on java

### ISSUE THREAD

**Issue by Josh65-2201** [Elikill58/Negativity#380]
### Which platform are you using ?

Paper

### Versions of Negativity and of the server

My version is: 2.6.1

### How did you made the false flag ?

1. Switch to creative mode
2. Fly
3. Teleport in the same world

### Can you show the proof file ?

[9aad764c-03e9-4c01-8336-0931d153c67e.txt](https://github.com/Elikill58/Negativity/files/11415590/9aad764c-03e9-4c01-8336-0931d153c67e.txt)

**Comment by Elikill58** [comment]
Fixed with https://github.com/Elikill58/Negativity/commit/562982fbdc03bba9cff5fc180fbb096a8a0a66d6
