### ISSUE TITLE
[FP]: InventoryMove

### ISSUE THREAD

**Issue by e-motiv** [Elikill58/Negativity#383]
### Which platform are you using ?

Paper

### Versions of Negativity and of the server

My version is:  1.19.4 Java

### How did you made the false flag ?

Step 1: I open my inventory and quickly change some stuff to the quick bar (with shift click or other addon)

Step 2: I just move and I get several of the lines below, not always with 100% reliability
- """New Warning for Stonee666 (99 ms, UUID: 5cf15099-f0e7-464e-b117-f2ab072bf638) seem to use InventoryMove 9 times Reliability: 100 [Stonee_Jungle: -18,-16,151]"""

(Step 3): When I open and close the inventory and move again, it's gone

### Can you show the proof file ?

My proof file:
[5cf15099-f0e7-464e-b117-f2ab072bf638.txt](https://github.com/Elikill58/Negativity/files/11489943/5cf15099-f0e7-464e-b117-f2ab072bf638.txt)

**Comment by Elikill58** [comment]
Fixed in https://github.com/Elikill58/Negativity/commit/b26c26756ca7f69900e34c35cb9f6600b29b4bf2
