### ISSUE TITLE
[Bug] Error Logs and Possible Conflict with Viaversion

### ISSUE THREAD

**Issue by Draghonir** [Elikill58/Negativity#391]
### Which platform are you using ?

Paper 1.20 V10

### Versions of Negativity and of the server

Negativity premium V 2.7

Hi, I hope you're doing well. I wanted to reach out to you and share some error logs I've come across. After doing some extensive research, I've identified a potential conflict with Viaversion. It seems that players who are not on version 1.20 are causing this error.

These errors specifically occur when players are using a different version than 1.20 with Viaversion. I've checked the server configurations and dependencies, and everything seems to be properly set up to support Viaversion. However, despite that, the error persists.

If you need any further information, please let me know. I hope we can work together to resolve this issue and improve the player experience on our server.

Thank you sincerely for your time and expertise. I'm grateful for your contribution in resolving this matter.

### Step to reproduce

play with other version

### Errors / Logs

https://haste.zendrique.fr/gojikitoba.apache

**Comment by Draghonir** [comment]
Confirmed by core team viaversion

<img width="889" alt="Capture d’écran 2023-06-12 120115" src="https://github.com/Elikill58/Negativity/assets/107469643/eee2bb96-257a-4c94-bdfe-6e2f3f44eb93">

**Comment by Elikill58** [comment]
Yes, it's well an issue from Negativity
