### ISSUE TITLE
Feature: Folia support

### ISSUE THREAD

**Issue by f3f5-dev** [Elikill58/Negativity#405]
### Are you using v2 (premium, 8€) ?

- [x] Yes I bought Negativity V2

### What is your idea ? What do you want ?

I would like adding a folia support, official paper  fork with new API (added to paper this api too)

### Why this idea ? Why it should be accepted ?

many plugins now support this like GrimAC

**Comment by Elikill58** [comment]
Do you have issue while using Negativity on Folia?

**Comment by f3f5-dev** [comment]
folia has new api also you need add to plugin.yml folia request
https://github.com/PaperMC/Folia

and folia api added officially to paperr api to faster support folia

**Comment by f3f5-dev** [comment]
@Elikill58 Any info about this?
folia support added: skinsrestorer(dev-build) , spark (dev-build) nocheatplus-updated and some other plugins
https://github.com/BlockhostOfficial/folia-plugins

**Comment by Elikill58** [comment]
The issue is that no Folia build are available for download easily, I'm mostly waiting for it. I'll try to get one soon

**Comment by f3f5-dev** [comment]
> The issue is that no Folia build are available for download easily, I'm mostly waiting for it. I'll try to get one soon

mini fork with download https://github.com/KaiijuMC/Kaiiju
