### ISSUE TITLE
Mega Bypass 

### ISSUE THREAD

**Issue by f3f5-dev** [Elikill58/Negativity#406]
### Versions of Negativity and of the server

negativity 2.7 paper 1.12.2

### What were you doing while finding bypass ?

https://workupload.com/file/9L3VMkv2qr3 video

### Which client with which mode ?

castom

**Comment by Elikill58** [comment]
I will close this in favor of #396 and #301 - The bypass seems to be for Jesus, and it's a known issue

**Comment by f3f5-dev** [comment]
@Elikill58 why this anticheat premium if anarchy clients bypassing it? are you planning fix?

**Comment by Elikill58** [comment]
Because all anticheat will always have bypass. It's premium because it's a recoded of free, with more plugin/platform support, more checks etc

**Comment by f3f5-dev** [comment]
> Because all anticheat will always have bypass. It's premium because it's a recoded of free, with more plugin/platform support, more checks etc

all anticheat always have bypass... but negaitivty fist ac when almost all
