### ISSUE TITLE
Npe

### ISSUE THREAD

**Issue by f3f5-dev** [Elikill58/Negativity#407]
### Which platform are you using ?

paper 1.12.2

### Versions of Negativity and of the server

Negativity 2.7

### Step to reproduce

![image](https://github.com/Elikill58/Negativity/assets/137526883/354e342d-1898-4d55-baa4-e414f83273fa)
i dont have full logs

### Errors / Logs

.

**Comment by Elikill58** [comment]
This is not a NPE but thanks for report. It seems to be created by a dependency, we'll see for update
