### ISSUE TITLE
[Bug] Errors when player leave or joins with Denizen plugin

### ISSUE THREAD

**Issue by Josh65-2201** [Elikill58/Negativity#413]
### Which platform are you using ?

Paper

### Versions of Negativity and of the server

Negativity 2.7.0
Paper 1.20.1 build 108

### Step to reproduce

1. Download https://ci.citizensnpcs.co/job/Denizen/
2. Join game
3. See null error

### Errors / Logs

[error.txt](https://github.com/Elikill58/Negativity/files/12448756/error.txt)

**Comment by Elikill58** [comment]
Failed to reproduce, seems to be because of another plugin

**Comment by Elikill58** [comment]
No way - Maybe fixed since or need more context

**Comment by Josh65-2201** [comment]
I have found new reproduce steps
1. Download https://ci.citizensnpcs.co/job/Denizen/
2. Download https://ci.citizensnpcs.co/job/Citizens2/
3. Put this script [errorScript.dsc.zip](https://github.com/Elikill58/Negativity/files/13459574/errorScript.dsc.zip) in plugins\Denizen\scripts
4. Start server
5. Join
6. Leave
7. See null error

**Comment by Elikill58** [comment]
After checking, for me it seems fixed with 2.7.1 even if I well have error with 2.7
