### ISSUE TITLE
Feature: Protocolize

### ISSUE THREAD

**Issue by 8MiYile** [Elikill58/Negativity#419]
### What is concerned ?

Plugins support

### Are you using v2 (premium, 8€) ?

- [ ] Yes I bought Negativity V2

### What is your idea ? What do you want ?

In the Velocity and BungeeCord server side, there is a plugin that works the same as the ProtocolLib plugin
https://www.spigotmc.org/resources/protocolize-protocollib-for-bungeecord-waterfall-velocity.63778/
I hope you guys will support this plugin

**Comment by Elikill58** [comment]
Hello,
1) The v1 is no longer supported, so it will not have new plugin support
2) What do you mean with "support" ? Do you have error with it?
3) It will not be useful to add it for v1. Maybe for v2, but the v1 (free) does not have any workaround for protocol on proxy

**Comment by 8MiYile** [comment]
@Elikill58 oh, i just say v2 version
if v2 can support, i will buy Negativity

**Comment by Elikill58** [comment]
The v2, as v1, doesn't need support for it. Also, there is no specific issue with it.
If you have issue, yes. But I don't want to support a plugin to say it's supported. There is no reason to specially support this.

**Comment by 8MiYile** [comment]
As I said, this plugin is for Velocity and BungeeCord because ProtocolLib doesn't support those two ends, only this plugin does (my personal opinion)

**Comment by Elikill58** [comment]
Yes, you're right. ProtocolLib doesn't support proxies. But, Negativity on proxy actually doesn't need ProtocolLib or anything like that
