### ISSUE TITLE
Bypasses (Skid)

### ISSUE THREAD

**Issue by tombola46** [Elikill58/Negativity#42]
**Describe the bug**
Fly Bypasses of Skid Hack Client (download:http://www.mediafire.com/file/15ignmy1rceg6nq/Skid.zip/file) - Modes : aac305,hac
Glide Bypasses - Modes : normal
Step Bypasses - Modes : all
Speed Bypasses - Modes : normal, aac335 lowhop, spartan bhop(but it is slow)/yport, aac339, aac332 fast yport, ncp bhop
Spider Bypasses - Modes : all
LongJump Bypasses - Modes : fiona

**Your plugin version**
1.4.1

**Your platform version (and precise the platforme (spigot/sponge))**
spigot 1.8.8

**Screenshots**
Please download the client and use it by your self to know how to fix this (because this client is using lots of people)

**Additional context**
Good Luck :)

**Comment by Elikill58** [comment]
Hello,
Thanks for your report, tomorrow i will check what i can do.

**Comment by Elikill58** [comment]
Glide and LongJump are not currently supported.
