### ISSUE TITLE
[FP]: VPN/Proxy check kicking me when I'm not using one

### ISSUE THREAD

**Issue by Josh65-2201** [Elikill58/Negativity#420]
### Which platform are you using ?

Paper

### Versions of Negativity and of the server

My version is: 2.7.2

### How did you made the false flag ?

1. Join server
2. Get kick (This doesn't happen all the time)

### Can you show the proof file ?

[proof.txt](https://github.com/Elikill58/Negativity/files/13540283/9aad764c-03e9-4c01-8336-0931d153c67e.txt)

**Comment by Elikill58** [comment]
Can you give me the IP used? To check manually

**Comment by Josh65-2201** [comment]
192.168.0.1

**Comment by Elikill58** [comment]
Should be fixed. As it's local IP, it were known as proxy
