### ISSUE TITLE
Feature: Minestom 1.20.5 support

### ISSUE THREAD

**Issue by MelonHell** [Elikill58/Negativity#425]
### What is concerned ?

Other

### Are you using v2 (premium, 8€) ?

- [X] Yes I bought Negativity V2

### What is your idea ? What do you want ?

The current version of Negativity only works with the legacy version of Minestom 1.19.3. I would like to see support for 1.20.5

**Comment by Elikill58** [comment]
Fixed with https://github.com/Elikill58/Negativity/commit/43ccc574a3f5f21582ac81d32f8805e095e4fab1
