### ISSUE TITLE
AntiKnockBack False Flag

### ISSUE THREAD

**Issue by tombola46** [Elikill58/Negativity#43]
**Describe the bug**
When you shoot arrow from your bow and it hits you you get flagged/kicked for AntiKnockBack

**Your plugin version**
1.4.1

**Your platform version (and precise the platforme (spigot/sponge))**
spigot 1.8.8

**Screenshots**
https://youtu.be/FCmuntamwuc

**Comment by coolpvpv1** [comment]
> **Describe the bug**
> When you shoot arrow from your bow and it hits you you get flagged/kicked for AntiKnockBack
> 
> **Your plugin version**
> 1.4.1
> 
> **Your platform version (and precise the platforme (spigot/sponge))**
> spigot 1.8.8
> 
> **Screenshots**
> https://youtu.be/FCmuntamwuc

try redownloading negativity from spigot delete your negativty folder get in a boat and try that again cause i cant false it
