### ISSUE TITLE
console errors reeeeeeeee

### ISSUE THREAD

**Issue by coolpvpv1** [Elikill58/Negativity#44]
Describe the bug
console errors reeeeeeeee

Your plugin version
1.4.1

Your platform version (and precise the platforme (spigot/sponge))
spigot 1.8.8

Screenshots
no

Error / Logs
https://paste.ubuntu.com/p/b9PDpy4xkR/

Additional context
no

**Comment by Elikill58** [comment]
Wtf, it's not the latest version of Negativity that's your using

**Comment by coolpvpv1** [comment]
> Wtf, it's not the latest version of Negativity that's your using

it is the latest i downloaded it from the spigotmc page and put it on 1.8.8 what do you mean

**Comment by Elikill58** [comment]
Mmmhhh it's very strange

**Comment by RedNesto** [comment]
Hi, we can't reproduce this issue and never heard of something similar before, we need full logs to have a chance to understand why this happened.
Of course you can remove all private information if needed.

**Comment by RedNesto** [comment]
Closing because we got no response.
