### ISSUE TITLE
Pixelmon-MOD support is required.

### ISSUE THREAD

**Issue by 850416511** [Elikill58/Negativity#46]
When running on a pixelmon server with flight auto detection enabled, the player will be kicked out of the game for riding a genie. For example, retracting an elf while riding on it will get you kicked out of the game. Is there a better solution?I don't know if players with FLY permission will be kicked out of the game. This is really a great plugin. I need it to work better. Thank you for your efforts.

**Comment by RedNesto** [comment]
Hi,

About the first example, the fly detection should not flag players riding an entity, and does not kick offenders by default (check `cheats.fly.kick` in your configuration). This could be the vanilla server kicking those players (the `allow-flight` in the server.properties).

About the second one, I got sometimes flagged for nofall when dismounting a flying pokémon, I may be able to make an exception if the player just dismounted an entity.

Also I assumed you used SpongeForge and PixelmonReforged. If this is not the case please tell me, results may vary. And don't forget to indicate what platform/mods/plugin version you use in the issues description ;)

**Comment by RedNesto** [comment]
I reduced the reliability if the player dismounted their vehicule in the last 3 ticks, I hope this is enough for your case.

If it is not, you can open a new issue.
