### ISSUE TITLE
NoPitchLimit Check

### ISSUE THREAD

**Issue by coolpvpv1** [Elikill58/Negativity#47]
It's about :
- [X] New detection

Explain the feature that you want
A NoPitchLimit Check sense it only takes 2 lines of code to make

Additional context
Its simple its just like 2 lines of code to detect it so i thought i should request this check

**Comment by Elikill58** [comment]
Hello,
What is the utility of this cheat ? Why block it ?

**Comment by coolpvpv1** [comment]
> Hello,
> What is the utility of this cheat ? Why block it ?

its a simple check to make so i mean why not

**Comment by Elikill58** [comment]
> > Hello,
> > What is the utility of this cheat ? Why block it ?
> its a simple check to make so i mean why not

I'm not sure about that, but i will try. Just, it's not my priority.
