### ISSUE TITLE
AirJump False Positive and suggestion

### ISSUE THREAD

**Issue by coolpvpv1** [Elikill58/Negativity#61]
**Describe the bug**
on 1.15.2 i was flying around with elytra and used a firework rocket going up and falsed air jump a ton and btw you should remove the spaces in the name so it doesn't cause bugs

**Your plugin version**
The version of Negativity that you are using 1.5

**Your platform version (and precise the platforme (spigot/sponge))**
The version of your server spigot 1.15.2

**Screenshots**

**Error / Logs**
If applicable, add logs of error (copy/paste on pastebin/hastebin).

**Additional context**
idk

**Comment by Elikill58** [comment]
For the name, you cand edit it in the config (to remove the space). And for the false positive, thanks you I will fix it.

**Comment by RedNesto** [comment]
The space in the name should be removed, it messes up the `/negativity verif` completion, it's also inconsistent with other names.
