### ISSUE TITLE
Flux Bypasses

### ISSUE THREAD

**Issue by tombola46** [Elikill58/Negativity#72]
**Describe the bug**
List of Bypasses of Flux Hack Client (Download : https://www.mediafire.com/file/lqmbtobl646yvcz/Flux_B14.rar/file)
Speed :
- HypixelHop2, Janitor, Latest, Swift, Hypixel, Mineplex, HypixelYPort, AACYPort

Nuker (BreakAura) :
- Bed - Range 4

Step : 
- Expand

Fly : 
- Float, OldFloat, Hypixel, Watchdoge

Spider :
- Vanilla

**Your plugin version**
1.5.1

**Your platform version (and precise the platforme (spigot/sponge))**
1.8.8 Spigot

**Screenshots**
Speed (one of onground) - https://streamable.com/73jli
Speed (one of bhop) - https://streamable.com/3ccuu
Speed (one of yport) - https://streamable.com/gpqcg
Spider - https://streamable.com/h5xic
Step - https://streamable.com/8dqsh

**Error / Logs**
none

**Additional context**
I will try to make new Fly check(for these bypassing) so please force on the speed bypasses

**Comment by Elikill58** [comment]
Detection updated :

Speed :
- [ ] Latest
- [ ] HypixelHop2
- [ ] Janitor
- [ ] Swift
- [ ] Hypixel
- [ ] Mineplex
- [ ] HypixelYPort
- [ ] AACYPort

Nuker:
- [x] BreakAura: Bed - Range 4

Step:
- [x] Expand

Fly :
- [x] Float
- [x] OldFloat
- [x] Hypixel
- [x] Watchdoge

Spider :
- [x] Vanilla
