### ISSUE TITLE
FastStairs False Flag

### ISSUE THREAD

**Issue by tombola46** [Elikill58/Negativity#73]
**Describe the bug**
When you are on stairs and spamming Space getting flagged

**Your plugin version**
1.5.1

**Your platform version (and precise the platforme (spigot/sponge))**
1.8.8 Spigot

**Screenshots**
https://streamable.com/us9fh

**Error / Logs**
https://paste.ubuntu.com/p/YFznTPmSg3/

**Additional context**
none

**Comment by Elikill58** [comment]
Hello,

Thanks for report, but i fix it in this commit: https://github.com/Elikill58/Negativity/commit/fc5493712287d69e0a61bd37ae3bb343f88c73d4 .

(Duplicated of #71 )

Just, the logs sent are for AirJump, not FastStairs ;)
