### ISSUE TITLE
Speed False Flag

### ISSUE THREAD

**Issue by tombola46** [Elikill58/Negativity#75]
**Describe the bug**
When you are on ice and under a slab,trapdoor(and idk if another blocks) and you are jumping and jump off the slab,trapdoor,etc you get flagged.

**Your plugin version**
1.5.1

**Your platform version (and precise the platforme (spigot/sponge))**
Spigot 1.8.8

**Screenshots**
https://streamable.com/cj56t

**Error / Logs**
https://paste.ubuntu.com/p/shrSPjhQCN/

**Additional context**
none

**Comment by Elikill58** [comment]
Hello,
Fly alert comes from NegativityAddon.

'DikDikDik' xD

**Comment by tombola46** [comment]
It is because Negativity not my addon.
Watch - https://streamable.com/9of5k
