### ISSUE TITLE
AutoSteal problems

### ISSUE THREAD

**Issue by Elikill58** [Elikill58/Negativity#76]
**Describe the bug**
False positive for AutoSteal on double click

**Your plugin version**
1.5.1

**Your platform version (and precise the platforme (spigot/sponge))**
1.8

**Comment by tombola46** [comment]
but when you are using double click you are not legit and many servers dont allow this :D

**Comment by Elikill58** [comment]
Really ?? Don't allow double click ??

**Comment by tombola46** [comment]
Like i dont know but i think that double click is not fair

**Comment by Elikill58** [comment]
Failed to reproduce, maybe fixed in update.
