### ISSUE TITLE
Size for custom inventory must be a multiple of 9 between 9 and 54 slots (got 90)

### ISSUE THREAD

**Issue by B4TT3RY** [Elikill58/Negativity#77]
**Describe the bug**
Clicked Button, Error

**Your plugin version**
1.5.1

**Your platform version (and precise the platforme (spigot/sponge))**
Paper-1.15.2 132 Build

**Screenshots**
![image](https://user-images.githubusercontent.com/12368101/76546049-2846f180-64ce-11ea-8b63-7236a778af77.png)

**Error / Logs**
If applicable, add logs of error (copy/paste on pastebin/hastebin).
https://hastebin.com/avanijoxic.sql

**Comment by Elikill58** [comment]
Hello,

Can you send me your plugin list ? It's very strange because it cannot appear by default.
