### ISSUE TITLE
Config is Empty

### ISSUE THREAD

**Issue by B4TT3RY** [Elikill58/Negativity#78]
**Your plugin version**
1.5.1

**Your platform version (and precise the platforme (spigot/sponge))**
Paper-1.15.2 132 Build

**Error / Logs**
https://hastebin.com/ucesiribuk.css

**Comment by Elikill58** [comment]
Hello,

Thanks for report. When the problem appear ? Have you update the plugin or it's only a new download ?

**Comment by RedNesto** [comment]
Do you have by any chance our proxy plugin installed without setting `hasBungeecord` to `false` in the configuration?

**Comment by B4TT3RY** [comment]
> Hello,
> 
> Thanks for report. When the problem appear ? Have you update the plugin or it's only a new download ?

New Download



> Do you have by any chance our proxy plugin installed without setting `hasBungeecord` to `true` in the configuration?

Nope

**Comment by RedNesto** [comment]
I'm not sure what your nope is responding to, but it is known bug when the companion plugin is installed (see #63).

**Comment by RedNesto** [comment]
It's been 20 days and I do not have enough information to pinpoint this issue. I assume it is fixed with #63 .
