### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by Katrix** [Elikill58/Negativity#82]
Not seeing any build files in the repo for use with Maven or Gradle. Are there any steps for building the plugin locally. Bit tired waiting for a new release with all the fixes.

**Comment by RedNesto** [comment]
You have to setup the project manually and download all dependencies (even if you are only interested by one platform). I know that's really bad, I want to improve the situation in the future but for now it's the only way.

**Comment by RedNesto** [comment]
If you need help setting up things you can send me a Discord PM or ask in the elikill's server.
