### ISSUE TITLE
Spider False Flag

### ISSUE THREAD

**Issue by tombola46** [Elikill58/Negativity#85]
**Describe the bug**
When you are climbing up a ladder you get false flagged for spider.

**Your plugin version**
1.5.2 (without addon)

**Your platform version (and precise the platforme (spigot/sponge))**
Spigot 1.8.8

**Screenshots**
none

**Error / Logs**
https://paste.ubuntu.com/p/Xr6pQcS6JH/

**Additional context**
none

**Comment by Elikill58** [comment]
Ouuupppssss, that's a pitty
