### ISSUE TITLE
FastStairs and Spider false flag

### ISSUE THREAD

**Issue by tombola46** [Elikill58/Negativity#86]
**Describe the bug**
When you are on stairs and pressing space(as on video) you are getting flagged for fast stairs and spider.

**Your plugin version**
1.5.2 (without addon)

**Your platform version (and precise the platforme (spigot/sponge))**
Spigot 1.8.8

**Screenshots**
https://streamable.com/2u6l6

**Error / Logs**
https://paste.ubuntu.com/p/hK5SD4wfFY/

**Additional context**
none

**Comment by Elikill58** [comment]
Just, "TPS: 26" ??

**Comment by tombola46** [comment]
Like i dont know why xD
