### ISSUE TITLE
NPE on EntityDamageByEntityEvent

### ISSUE THREAD

**Issue by Katrix** [Elikill58/Negativity#91]
**Describe the bug**
NPE on EntityDamageByEvent

**Your plugin version**
1.5.2

**Your platform version (and precise the platforme (spigot/sponge))**
Paper 1.14.4

**Error / Logs**
https://hastebin.com/iwafoniloy.sql

**Comment by Elikill58** [comment]
Duplicate of #90

**Comment by RRayzeRR** [comment]
yes, i oberserve the error came when player hit each others. its appear in 1.5.2

**Comment by Elikill58** [comment]
Yes, i didn't find it before the 1.5.2 update, and it have been fixed thanks to the report of #90
