### ISSUE TITLE
Speed depth strider FP

### ISSUE THREAD

**Issue by Katrix** [Elikill58/Negativity#92]
**Describe the bug**
A false positive involving speed and depth strider

**Your plugin version**
1.5.2

**Your platform version (and precise the platforme (spigot/sponge))**
Paper 1.14.4

**Screenshots**
https://cdn.discordapp.com/attachments/208296532976336897/693868276656373760/javaw_2020-03-29_18-02-22-371.mp4

**Comment by Katrix** [comment]
Update, seems to happen without depth strider too

**Comment by Elikill58** [comment]
Update: fixed in commit https://github.com/Elikill58/Negativity/commit/0fd1eaeee94da3f8c8baea3731dc771d17264c1c :)
