### ISSUE TITLE
Player join console error

### ISSUE THREAD

**Issue by eereeska** [Elikill58/Negativity#93]
(sorry for my eng)

**Describe the bug**
When player join, I receive this in the console

**Your plugin version**
1.5.2

**Your platform version (and precise the platforme (spigot/sponge))**
paper 1.14.4

**Screenshots**

**Error / Logs**
 WARN javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
30.03 16:34:02 [Server] WARN at sun.security.ssl.Alerts.getSSLException(Unknown Source)
30.03 16:34:02 [Server] WARN at sun.security.ssl.Alerts.getSSLException(Unknown Source)
30.03 16:34:02 [Server] WARN at sun.security.ssl.SSLSocketImpl.recvAlert(Unknown Source)
30.03 16:34:02 [Server] WARN at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
30.03 16:34:02 [Server] WARN at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)
30.03 16:34:02 [Server] WARN at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
30.03 16:34:02 [Server] WARN at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
30.03 16:34:02 [Server] WARN at sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source)
30.03 16:34:02 [Server] WARN at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
30.03 16:34:02 [Server] WARN at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
30.03 16:34:02 [Server] WARN at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
30.03 16:34:02 [Server] WARN at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
30.03 16:34:02 [Server] WARN at com.elikill58.negativity.universal.utils.UniversalUtils.lambda$0(UniversalUtils.java:183)
30.03 16:34:02 [Server] WARN at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
30.03 16:34:02 [Server] WARN at java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source)
30.03 16:34:02 [Server] WARN at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
30.03 16:34:02 [Server] WARN at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
30.03 16:34:02 [Server] WARN at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
30.03 16:34:02 [Server] WARN at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)

**Comment by Elikill58** [comment]
Hello,

That's strange because it appear when Negativity get McLeaks informations.
Her website seem to be UP, can you check if you can access to "https://mcleaks.themrgong.xyz/api/v3/isuuidmcleaks/195dbcbc-9f2e-389e-82c4-3d017795ca65" ?

**Comment by eereeska** [comment]
> Hello,
> 
> That's strange because it appear when Negativity get McLeaks informations.
> Her website seem to be UP, can you check if you can access to "https://mcleaks.themrgong.xyz/api/v3/isuuidmcleaks/195dbcbc-9f2e-389e-82c4-3d017795ca65" ?

Cant, sorry

**Comment by Elikill58** [comment]
can't check or can't access ? (the website must to send only "{"isMcleaks":false}")

**Comment by eereeska** [comment]
can't check

**Comment by Elikill58** [comment]
I know that yesterday, some hosting service was down. Tell me if the problem is already here even some day. Then, if the server is hosted by you (in local) check your firewall

**Comment by eereeska** [comment]
Not my host, buy yes, some hosting service was down
And the problem hasn't disappeared:

31.03 18:13:30 [Server] WARN javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
31.03 18:13:30 [Server] WARN at sun.security.ssl.Alerts.getSSLException(Unknown Source)
31.03 18:13:30 [Server] WARN at sun.security.ssl.Alerts.getSSLException(Unknown Source)
31.03 18:13:30 [Server] WARN at sun.security.ssl.SSLSocketImpl.recvAlert(Unknown Source)
31.03 18:13:30 [Server] WARN at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
31.03 18:13:30 [Server] WARN at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)
31.03 18:13:30 [Server] WARN at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
31.03 18:13:30 [Server] WARN at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
31.03 18:13:30 [Server] WARN at sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source)
31.03 18:13:30 [Server] WARN at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
31.03 18:13:30 [Server] WARN at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
31.03 18:13:30 [Server] WARN at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
31.03 18:13:30 [Server] WARN at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
31.03 18:13:30 [Server] WARN at com.elikill58.negativity.universal.utils.UniversalUtils.lambda$0(UniversalUtils.java:183)
31.03 18:13:30 [Server] WARN at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
31.03 18:13:30 [Server] WARN at java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source)
31.03 18:13:30 [Server] WARN at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
31.03 18:13:30 [Server] WARN at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
31.03 18:13:30 [Server] WARN at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
31.03 18:13:30 [Server] WARN at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
