### ISSUE TITLE
Could not pass event BlockBreakEvent to Negativity v1.5.2

### ISSUE THREAD

**Issue by eereeska** [Elikill58/Negativity#95]
**Your plugin version**
1.5.2

**Your platform version (and precise the platforme (spigot/sponge))**
paper, 1.14.4

**Error / Logs**
ERROR Could not pass event BlockBreakEvent to Negativity v1.5.2
31.03 16:44:04 [Server] INFO java.lang.NullPointerException: null
31.03 16:44:04 [Server] ERROR Could not pass event BlockBreakEvent to Negativity v1.5.2
31.03 16:44:04 [Server] INFO java.lang.NullPointerException: null
31.03 16:44:04 [Server] ERROR Could not pass event BlockBreakEvent to Negativity v1.5.2
31.03 16:44:04 [Server] INFO java.lang.NullPointerException: null

**Comment by Elikill58** [comment]
Hello,
There is only 2 lines for each breaked blocks ? Not more ?

**Comment by eereeska** [comment]
Have new ones:

31.03 18:14:54 [Server] ERROR Could not pass event BlockBreakEvent to Negativity v1.5.2
31.03 18:14:54 [Server] INFO java.lang.NullPointerException: null
31.03 18:14:54 [Server] INFO at com.elikill58.negativity.spigot.protocols.NukerProtocol.onBlockBreak(NukerProtocol.java:40) ~[?:?]
31.03 18:14:54 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor265.execute(Unknown Source) ~[?:?]
31.03 18:14:54 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-243]
31.03 18:14:54 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-243]
31.03 18:14:54 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-243]
31.03 18:14:54 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-243]
31.03 18:14:54 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:306) ~[patched_1.14.4.jar:git-Paper-243]
31.03 18:14:54 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerInteractManager.a(PlayerInteractManager.java:265) ~[patched_1.14.4.jar:git-Paper-243]
31.03 18:14:54 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerInteractManager.a(PlayerInteractManager.java:239) ~[patched_1.14.4.jar:git-Paper-243]
31.03 18:14:54 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1307) ~[patched_1.14.4.jar:git-Paper-243]
31.03 18:14:54 [Server] INFO at net.minecraft.server.v1_14_R1.PacketPlayInBlockDig.a(SourceFile:40) ~[patched_1.14.4.jar:git-Paper-243]
31.03 18:14:54 [Server] INFO at net.minecraft.server.v1_14_R1.PacketPlayInBlockDig.a(SourceFile:10) ~[patched_1.14.4.jar:git-Paper-243]
31.03 18:14:54 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.14.4.jar:git-Paper-243]
31.03 18:14:54 [Server] INFO at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.4.jar:git-Paper-243]
31.03 18:14:54 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.14.4.jar:git-Paper-243]
31.03 18:14:54 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.4.jar:git-Paper-243]
31.03 18:14:54 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.14.4.jar:git-Paper-243]
31.03 18:14:54 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1029) ~[patched_1.14.4.jar:git-Paper-243]
31.03 18:14:54 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1022) ~[patched_1.14.4.jar:git-Paper-243]
31.03 18:14:54 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.14.4.jar:git-Paper-243]
31.03 18:14:54 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1088) ~[patched_1.14.4.jar:git-Paper-243]
31.03 18:14:54 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925) ~[patched_1.14.4.jar:git-Paper-243]

**Comment by Elikill58** [comment]
And what you was doing ? It's seem to don't find the breaked block

**Comment by eereeska** [comment]
That wasn't me

**Comment by Elikill58** [comment]
Ok
