### ISSUE TITLE
Message not send on chat

### ISSUE THREAD

**Issue by Elikill58** [Elikill58/Negativity#96]
**Describe the bug**
Any message are send on the chat when "Chat" is enabled wit setback option (even good message)

**Your plugin version**
1.5.2

**Your platform version (and precise the platforme (spigot/sponge))**
Paper 1.15.2

**Additional context**
Report by: mntain#8883 on discord

**Comment by bertugarangou** [comment]
Problem solved resetting config file. Sorry for any inconvenience.
